// ═══════════════════════════════════════════════════════════════════════════
//  MAISTO DUOMENŲ BAZĖ  –  visos vertės per 100g
// ═══════════════════════════════════════════════════════════════════════════

export const LOCAL_FOODS = [

  // ── KIAUŠINIAI ────────────────────────────────────────────────────────────
  { id:"egg_m",      name:"Kiaušinis (vidutinis)",       category:"Kiaušiniai", kcal:143, protein:12.6, fat:9.5,  carbs:0.7, units:[{label:"1 vnt (55g)",grams:55},{label:"2 vnt",grams:110},{label:"3 vnt",grams:165}] },
  { id:"egg_l",      name:"Kiaušinis (didelis)",         category:"Kiaušiniai", kcal:143, protein:12.6, fat:9.5,  carbs:0.7, units:[{label:"1 vnt (65g)",grams:65},{label:"2 vnt",grams:130},{label:"3 vnt",grams:195}] },
  { id:"egg_white",  name:"Kiaušinio baltymas",          category:"Kiaušiniai", kcal:52,  protein:10.9, fat:0.2,  carbs:0.7, units:[{label:"1 vnt (33g)",grams:33},{label:"2 vnt",grams:66},{label:"4 vnt",grams:132}] },
  { id:"egg_yolk",   name:"Kiaušinio trynys",            category:"Kiaušiniai", kcal:322, protein:15.9, fat:26.5, carbs:3.6, units:[{label:"1 vnt (18g)",grams:18},{label:"2 vnt",grams:36}] },
  { id:"egg_scr",    name:"Kiaušinienė (2 kiaušiniai)",  category:"Kiaušiniai", kcal:148, protein:10,   fat:11,   carbs:1.6, units:[{label:"1 porcija (130g)",grams:130}] },
  { id:"egg_hard",   name:"Kiaušinis kietai virtas",     category:"Kiaušiniai", kcal:155, protein:13,   fat:11,   carbs:1.1, units:[{label:"1 vnt (50g)",grams:50},{label:"2 vnt",grams:100}] },
  { id:"egg_poach",  name:"Kiaušinis pochė",             category:"Kiaušiniai", kcal:143, protein:12.6, fat:9.5,  carbs:0.7, units:[{label:"1 vnt (50g)",grams:50}] },

  // ── VIŠTIENA ──────────────────────────────────────────────────────────────
  { id:"chick_br_r", name:"Vištienos krūtinėlė (žalia)", category:"Mėsa – vištiena", kcal:120, protein:22.5, fat:2.6,  carbs:0, units:[{label:"1 filė (150g)",grams:150},{label:"1 filė (200g)",grams:200}] },
  { id:"chick_br_c", name:"Vištienos krūtinėlė (virta)", category:"Mėsa – vištiena", kcal:165, protein:31,   fat:3.6,  carbs:0, units:[{label:"1 porcija (150g)",grams:150},{label:"½ porcija",grams:75}] },
  { id:"chick_br_b", name:"Vištienos krūtinėlė (kepta)", category:"Mėsa – vištiena", kcal:195, protein:29,   fat:8.5,  carbs:0, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"chick_th_c", name:"Vištienos šlaunelė (virta)",  category:"Mėsa – vištiena", kcal:209, protein:26,   fat:11,   carbs:0, units:[{label:"1 vnt (100g)",grams:100},{label:"2 vnt",grams:200}] },
  { id:"chick_th_b", name:"Vištienos šlaunelė (kepta, su oda)", category:"Mėsa – vištiena", kcal:247, protein:25, fat:16, carbs:0, units:[{label:"1 vnt (120g)",grams:120}] },
  { id:"chick_wing", name:"Vištienos sparneliai (kepti)", category:"Mėsa – vištiena", kcal:290, protein:27,   fat:19,   carbs:0, units:[{label:"2 vnt (80g)",grams:80},{label:"4 vnt",grams:160}] },
  { id:"chick_min",  name:"Vištienos maltinukai",         category:"Mėsa – vištiena", kcal:143, protein:17,   fat:8,    carbs:0, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"turkey_br",  name:"Kalakutiena (krūtinėlė, virta)", category:"Mėsa – vištiena", kcal:189, protein:29, fat:7.4, carbs:0, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"saus_chick", name:"Vištienos dešrelė (virta)",   category:"Mėsa – vištiena", kcal:172, protein:14,   fat:12,   carbs:2, units:[{label:"1 vnt (60g)",grams:60},{label:"2 vnt",grams:120}] },
  { id:"chick_liver",name:"Vištų kepenėlės (keptos)",    category:"Mėsa – vištiena", kcal:172, protein:24.5, fat:7.6,  carbs:0.9, units:[{label:"1 porcija (100g)",grams:100}] },
  { id:"chick_mince",name:"Vištienos faršas (žalias)",   category:"Mėsa – vištiena", kcal:143, protein:17.4, fat:8.1,  carbs:0, units:[{label:"1 porcija (150g)",grams:150}] },

  // ── JAUTIENA / KIAULIENA ──────────────────────────────────────────────────
  { id:"beef_lean",  name:"Jautiena liesa (virta)",       category:"Mėsa – raudona", kcal:215, protein:26,   fat:12,   carbs:0, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"beef_min",   name:"Jautienos faršas (10% riebalų)", category:"Mėsa – raudona", kcal:215, protein:21, fat:14,   carbs:0, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"beef_min20", name:"Jautienos faršas (20% riebalų)", category:"Mėsa – raudona", kcal:267, protein:17, fat:22,   carbs:0, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"beef_steak", name:"Jautienos kepsnys liesas (keptas)", category:"Mėsa – raudona", kcal:207, protein:27, fat:11, carbs:0, units:[{label:"1 kepsnys (180g)",grams:180}] },
  { id:"beef_liver", name:"Jautienos kepenys (keptos)",   category:"Mėsa – raudona", kcal:175, protein:26.5, fat:5.9,  carbs:4.9, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"beef_rib",   name:"Jautienos šonkauliai (kepti)", category:"Mėsa – raudona", kcal:291, protein:24,   fat:21,   carbs:0, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"pork_lean",  name:"Kiauliena liesa (virta)",      category:"Mėsa – raudona", kcal:242, protein:27,   fat:14,   carbs:0, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"pork_ch",    name:"Kiaulienos kotletas (keptas)", category:"Mėsa – raudona", kcal:280, protein:25,   fat:19,   carbs:0, units:[{label:"1 vnt (130g)",grams:130}] },
  { id:"pork_belly", name:"Kiaulienos pilvas (keptas)",   category:"Mėsa – raudona", kcal:518, protein:15,   fat:51,   carbs:0, units:[{label:"1 porcija (100g)",grams:100}] },
  { id:"pork_shldr", name:"Kiaulienos mentė (virta)",     category:"Mėsa – raudona", kcal:248, protein:27,   fat:15,   carbs:0, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"bacon",      name:"Bekono juostelės (keptos)",    category:"Mėsa – raudona", kcal:541, protein:37,   fat:42,   carbs:1.4, units:[{label:"2 juostelės (20g)",grams:20},{label:"4 juostelės",grams:40}] },
  { id:"lamb_leg",   name:"Ėrienos koja (virta)",         category:"Mėsa – raudona", kcal:218, protein:29,   fat:10.7, carbs:0, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"lamb_chop",  name:"Ėrienos kotletas (keptas)",    category:"Mėsa – raudona", kcal:294, protein:25,   fat:21,   carbs:0, units:[{label:"1 kotletas (120g)",grams:120}] },
  { id:"veal_cut",   name:"Veršienos kotletas (keptas)",  category:"Mėsa – raudona", kcal:196, protein:30,   fat:8,    carbs:0, units:[{label:"1 kotletas (130g)",grams:130}] },
  { id:"duck_br",    name:"Ančiukų krūtinėlė (kepta)",   category:"Mėsa – raudona", kcal:201, protein:28,   fat:10,   carbs:0, units:[{label:"1 filė (150g)",grams:150}] },
  { id:"venison",    name:"Elnio mėsa (virta)",           category:"Mėsa – raudona", kcal:187, protein:30,   fat:7,    carbs:0, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"rabbit",     name:"Triušiena (virta)",            category:"Mėsa – raudona", kcal:197, protein:33,   fat:6.6,  carbs:0, units:[{label:"1 porcija (150g)",grams:150}] },

  // ── ŽUVIS IR JŪROS GĖRYBĖS ────────────────────────────────────────────────
  { id:"tuna_can",   name:"Tunas vandenyje (konservuotas)", category:"Žuvis", kcal:116, protein:26,   fat:0.5,  carbs:0, units:[{label:"1 skardinė (160g)",grams:160},{label:"½ skardinė",grams:80}] },
  { id:"tuna_oil",   name:"Tunas aliejuje (konservuotas)", category:"Žuvis",  kcal:198, protein:25,   fat:10,   carbs:0, units:[{label:"1 skardinė (160g)",grams:160}] },
  { id:"tuna_fresh", name:"Tunas šviežias (keptas)",       category:"Žuvis",  kcal:184, protein:30,   fat:6.5,  carbs:0, units:[{label:"1 filė (150g)",grams:150}] },
  { id:"salmon_c",   name:"Lašiša (kepta)",                category:"Žuvis",  kcal:206, protein:20,   fat:13,   carbs:0, units:[{label:"1 filė (150g)",grams:150},{label:"1 filė (200g)",grams:200}] },
  { id:"salmon_raw", name:"Lašiša šviežia (žalia)",        category:"Žuvis",  kcal:208, protein:20,   fat:13.4, carbs:0, units:[{label:"1 filė (150g)",grams:150}] },
  { id:"salmon_smo", name:"Lašiša rūkyta",                 category:"Žuvis",  kcal:142, protein:22.5, fat:5.8,  carbs:0, units:[{label:"3 riekelės (60g)",grams:60},{label:"6 riekelės",grams:120}] },
  { id:"cod",        name:"Menkė (virta)",                  category:"Žuvis",  kcal:105, protein:23,   fat:0.9,  carbs:0, units:[{label:"1 filė (150g)",grams:150}] },
  { id:"herring",    name:"Silkė (marinuota)",              category:"Žuvis",  kcal:158, protein:17,   fat:9,    carbs:2.5, units:[{label:"1 filė (80g)",grams:80},{label:"2 filės",grams:160}] },
  { id:"herring_smo",name:"Silkė rūkyta",                  category:"Žuvis",  kcal:185, protein:21,   fat:11,   carbs:0, units:[{label:"1 filė (80g)",grams:80}] },
  { id:"shrimp",     name:"Krevetės (virtos)",              category:"Žuvis",  kcal:99,  protein:24,   fat:0.3,  carbs:0.2, units:[{label:"1 porcija (150g)",grams:150},{label:"½ porcija",grams:75}] },
  { id:"mackerel",   name:"Skumbrė (rūkyta)",              category:"Žuvis",  kcal:305, protein:19,   fat:25,   carbs:0, units:[{label:"1 filė (120g)",grams:120}] },
  { id:"mackerel_c", name:"Skumbrė (konservuota, aliejuje)", category:"Žuvis", kcal:239, protein:18.7, fat:18.3, carbs:0, units:[{label:"1 skardinė (125g)",grams:125}] },
  { id:"trout",      name:"Upėtakis (keptas)",              category:"Žuvis",  kcal:190, protein:26,   fat:9,    carbs:0, units:[{label:"1 filė (150g)",grams:150}] },
  { id:"carp",       name:"Karpis (virtas)",                category:"Žuvis",  kcal:162, protein:22,   fat:8,    carbs:0, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"pike",       name:"Lydeka (virta)",                 category:"Žuvis",  kcal:113, protein:24.7, fat:1.2,  carbs:0, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"perch",      name:"Ešerys / Starkis (virtas)",      category:"Žuvis",  kcal:117, protein:24,   fat:2,    carbs:0, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"sardines",   name:"Sardinės (konservuotos, aliejuje)", category:"Žuvis", kcal:208, protein:24.6, fat:11.5, carbs:0, units:[{label:"1 skardinė (125g)",grams:125},{label:"½ skardinė",grams:62}] },
  { id:"tilapia",    name:"Tilapija (kepta)",               category:"Žuvis",  kcal:128, protein:26,   fat:2.7,  carbs:0, units:[{label:"1 filė (150g)",grams:150}] },
  { id:"pollock",    name:"Poliakas (keptas)",              category:"Žuvis",  kcal:111, protein:23,   fat:1.3,  carbs:0, units:[{label:"1 filė (150g)",grams:150}] },
  { id:"flounder",   name:"Otas / Plekšnė (kepta)",        category:"Žuvis",  kcal:91,  protein:18.8, fat:1.2,  carbs:0, units:[{label:"1 filė (120g)",grams:120}] },
  { id:"mussels",    name:"Midijos (virtos)",               category:"Žuvis",  kcal:172, protein:24,   fat:4.5,  carbs:7.4, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"squid",      name:"Kalmarai (kepti)",               category:"Žuvis",  kcal:175, protein:18,   fat:7.5,  carbs:7.5, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"octopus",    name:"Aštuonkojis (virtas)",           category:"Žuvis",  kcal:164, protein:30,   fat:2.1,  carbs:4.4, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"oysters",    name:"Austres (žalios)",               category:"Žuvis",  kcal:69,  protein:7,    fat:2.5,  carbs:3.9, units:[{label:"6 vnt (90g)",grams:90}] },
  { id:"eel_smo",    name:"Ungurys rūkytas",                category:"Žuvis",  kcal:290, protein:18.4, fat:24.2, carbs:0, units:[{label:"1 porcija (100g)",grams:100}] },
  { id:"catfish",    name:"Šamas (keptas)",                 category:"Žuvis",  kcal:144, protein:18,   fat:7.6,  carbs:0, units:[{label:"1 filė (150g)",grams:150}] },
  { id:"crab",       name:"Krabų mėsa (virta)",             category:"Žuvis",  kcal:97,  protein:19,   fat:1.8,  carbs:0, units:[{label:"1 porcija (120g)",grams:120}] },
  { id:"lobster",    name:"Omaras (virtas)",                category:"Žuvis",  kcal:89,  protein:19,   fat:0.9,  carbs:0, units:[{label:"1 porcija (150g)",grams:150}] },

  // ── PIENO PRODUKTAI ──────────────────────────────────────────────────────
  { id:"cottage_5",  name:"Varškė 5%",                      category:"Pieno produktai", kcal:103, protein:11,   fat:4.5,  carbs:3.4, units:[{label:"½ puodelis (120g)",grams:120},{label:"1 puodelis (240g)",grams:240}] },
  { id:"cottage_0",  name:"Varškė 0%",                      category:"Pieno produktai", kcal:72,  protein:12.4, fat:0.3,  carbs:3.4, units:[{label:"½ puodelis (120g)",grams:120},{label:"1 puodelis (240g)",grams:240}] },
  { id:"cottage_9",  name:"Varškė 9%",                      category:"Pieno produktai", kcal:174, protein:9,    fat:9,    carbs:3.5, units:[{label:"½ puodelis (120g)",grams:120}] },
  { id:"greek_0",    name:"Graikiškas jogurtas 0%",         category:"Pieno produktai", kcal:59,  protein:10.2, fat:0.4,  carbs:3.6, units:[{label:"1 indelis (150g)",grams:150},{label:"1 puodelis (200g)",grams:200}] },
  { id:"greek_2",    name:"Graikiškas jogurtas 2%",         category:"Pieno produktai", kcal:73,  protein:9.9,  fat:1.9,  carbs:3.6, units:[{label:"1 indelis (150g)",grams:150}] },
  { id:"skyr",       name:"Skyr (islandiškas jogurtas)",    category:"Pieno produktai", kcal:63,  protein:11,   fat:0.2,  carbs:4,   units:[{label:"1 indelis (150g)",grams:150},{label:"1 didelis (200g)",grams:200}] },
  { id:"jogurt_nat", name:"Natūralus jogurtas",             category:"Pieno produktai", kcal:61,  protein:3.5,  fat:3.3,  carbs:4.7, units:[{label:"1 indelis (150g)",grams:150},{label:"1 puodelis (200g)",grams:200}] },
  { id:"jogurt_fr",  name:"Vaisinis jogurtas",              category:"Pieno produktai", kcal:100, protein:3.2,  fat:2.5,  carbs:17,  units:[{label:"1 indelis (125g)",grams:125}] },
  { id:"milk_35",    name:"Pienas 3,5%",                    category:"Pieno produktai", kcal:61,  protein:3.2,  fat:3.5,  carbs:4.8, units:[{label:"1 stiklinė (200ml)",grams:200},{label:"½ stiklinė",grams:100}] },
  { id:"milk_15",    name:"Pienas 1,5%",                    category:"Pieno produktai", kcal:46,  protein:3.3,  fat:1.5,  carbs:4.8, units:[{label:"1 stiklinė (200ml)",grams:200}] },
  { id:"milk_0",     name:"Liesas pienas 0,5%",             category:"Pieno produktai", kcal:35,  protein:3.4,  fat:0.5,  carbs:5.0, units:[{label:"1 stiklinė (200ml)",grams:200}] },
  { id:"kefir",      name:"Kefyras",                        category:"Pieno produktai", kcal:52,  protein:3.3,  fat:1.5,  carbs:4.8, units:[{label:"1 stiklinė (200ml)",grams:200}] },
  { id:"buttermilk", name:"Sviestpienė",                    category:"Pieno produktai", kcal:40,  protein:3.3,  fat:0.9,  carbs:4.8, units:[{label:"1 stiklinė (200ml)",grams:200}] },
  { id:"ayran",      name:"Ayran (geriamasis jogurtas)",    category:"Pieno produktai", kcal:40,  protein:2.8,  fat:1.5,  carbs:4,   units:[{label:"1 buteliukas (200ml)",grams:200}] },
  { id:"cheese_ch",  name:"Čederio sūris",                  category:"Pieno produktai", kcal:402, protein:25,   fat:33,   carbs:1.3, units:[{label:"1 riekelė (30g)",grams:30},{label:"2 riekelės",grams:60}] },
  { id:"mozz",       name:"Mocarela (lengva)",              category:"Pieno produktai", kcal:254, protein:28,   fat:15,   carbs:2.8, units:[{label:"1 rutuliukas (80g)",grams:80}] },
  { id:"parmes",     name:"Parmezanas (tarkuotas)",         category:"Pieno produktai", kcal:431, protein:38,   fat:29,   carbs:3.2, units:[{label:"1 šaukštas (10g)",grams:10},{label:"2 šaukštai",grams:20}] },
  { id:"feta",       name:"Feta sūris",                     category:"Pieno produktai", kcal:264, protein:14.2, fat:21.3, carbs:4.1, units:[{label:"1 porcija (50g)",grams:50},{label:"2 porcijos",grams:100}] },
  { id:"brie",       name:"Brie sūris",                     category:"Pieno produktai", kcal:334, protein:20.7, fat:27.7, carbs:0.5, units:[{label:"1 riekelė (30g)",grams:30}] },
  { id:"camembert",  name:"Camembert sūris",                category:"Pieno produktai", kcal:300, protein:19.8, fat:24.3, carbs:0.5, units:[{label:"1 riekelė (30g)",grams:30}] },
  { id:"gouda",      name:"Gouda sūris",                    category:"Pieno produktai", kcal:356, protein:25,   fat:27.4, carbs:2.2, units:[{label:"1 riekelė (30g)",grams:30},{label:"2 riekelės",grams:60}] },
  { id:"emmental",   name:"Emmental sūris",                 category:"Pieno produktai", kcal:380, protein:28.8, fat:29.1, carbs:1.5, units:[{label:"1 riekelė (30g)",grams:30}] },
  { id:"halloumi",   name:"Halloumi (keptas)",              category:"Pieno produktai", kcal:321, protein:21.4, fat:25.9, carbs:0.8, units:[{label:"2 riekelės (60g)",grams:60}] },
  { id:"mascarpone", name:"Mascarpone",                     category:"Pieno produktai", kcal:429, protein:4.8,  fat:44.6, carbs:2.5, units:[{label:"1 šaukštas (30g)",grams:30}] },
  { id:"ricotta",    name:"Ricotta",                        category:"Pieno produktai", kcal:174, protein:11.3, fat:13,   carbs:3,   units:[{label:"½ puodelis (120g)",grams:120}] },
  { id:"cream_ch",   name:"Grietinėlės sūris",             category:"Pieno produktai", kcal:342, protein:6,    fat:34,   carbs:4,   units:[{label:"1 šaukštas (30g)",grams:30}] },
  { id:"sour_cr",    name:"Grietinė 15%",                   category:"Pieno produktai", kcal:163, protein:2.7,  fat:15,   carbs:3.8, units:[{label:"1 šaukštas (25g)",grams:25},{label:"2 šaukštai",grams:50}] },
  { id:"sour_cr30",  name:"Grietinė 30%",                   category:"Pieno produktai", kcal:292, protein:2.5,  fat:30,   carbs:3.5, units:[{label:"1 šaukštas (25g)",grams:25}] },
  { id:"cream35",    name:"Grietinėlė 35%",                 category:"Pieno produktai", kcal:340, protein:2.2,  fat:35,   carbs:2.8, units:[{label:"2 šaukštai (30g)",grams:30}] },
  { id:"butter",     name:"Sviestas",                       category:"Pieno produktai", kcal:717, protein:0.5,  fat:81,   carbs:0.1, units:[{label:"1 šaukštelis (5g)",grams:5},{label:"1 šaukštas (15g)",grams:15}] },
  { id:"butter_lt",  name:"Sviestas lengvas (60%)",         category:"Pieno produktai", kcal:536, protein:0.5,  fat:60,   carbs:0.5, units:[{label:"1 šaukštas (15g)",grams:15}] },
  { id:"condensed",  name:"Kondensuotas pienas (su cukrumi)", category:"Pieno produktai", kcal:321, protein:8.1, fat:8.7, carbs:54.4, units:[{label:"1 šaukštas (20g)",grams:20}] },
  { id:"prot_powder",name:"Baltymų milteliai (whey)",       category:"Pieno produktai", kcal:380, protein:75,   fat:5,    carbs:8,   units:[{label:"1 porcija (30g)",grams:30}] },
  { id:"prot_casm",  name:"Baltymų milteliai (kazein)",     category:"Pieno produktai", kcal:363, protein:78,   fat:2.5,  carbs:5.5, units:[{label:"1 porcija (30g)",grams:30}] },
  { id:"varskes_sur",name:"Varškės sūrelis glazūruotas",    category:"Pieno produktai", kcal:290, protein:9,    fat:17,   carbs:27,  units:[{label:"1 vnt (40g)",grams:40}] },

  // ── GRŪDAI ───────────────────────────────────────────────────────────────
  { id:"oats_dry",   name:"Avižiniai dribsniai (sausi)",    category:"Grūdai", kcal:389, protein:17,   fat:7,    carbs:66,  units:[{label:"½ puodelio (40g)",grams:40},{label:"1 puodelis (80g)",grams:80}] },
  { id:"oats_inst",  name:"Avižiniai dribsniai momentiniai", category:"Grūdai", kcal:371, protein:13.2, fat:6.5, carbs:67, units:[{label:"1 paketėlis (35g)",grams:35}] },
  { id:"rice_wh",    name:"Ryžiai balti (virti)",           category:"Grūdai", kcal:130, protein:2.7,  fat:0.3,  carbs:28,  units:[{label:"½ puodelio (100g)",grams:100},{label:"1 puodelis (200g)",grams:200}] },
  { id:"rice_br",    name:"Ryžiai rudieji (virti)",         category:"Grūdai", kcal:122, protein:2.6,  fat:1,    carbs:26,  units:[{label:"½ puodelio (100g)",grams:100},{label:"1 puodelis (200g)",grams:200}] },
  { id:"rice_jasmin",name:"Ryžiai jazmino (virti)",         category:"Grūdai", kcal:130, protein:2.7,  fat:0.3,  carbs:28,  units:[{label:"½ puodelio (100g)",grams:100}] },
  { id:"rice_basm",  name:"Ryžiai basmati (virti)",         category:"Grūdai", kcal:121, protein:2.5,  fat:0.3,  carbs:26,  units:[{label:"½ puodelio (100g)",grams:100}] },
  { id:"pasta_c",    name:"Makaronai (virti)",              category:"Grūdai", kcal:158, protein:5.8,  fat:0.9,  carbs:31,  units:[{label:"1 porcija (200g)",grams:200},{label:"½ porcija",grams:100}] },
  { id:"pasta_wh",   name:"Makaronai iš kviečių (virti)",  category:"Grūdai", kcal:124, protein:5.3,  fat:0.5,  carbs:26,  units:[{label:"1 porcija (200g)",grams:200}] },
  { id:"soba",       name:"Soba makaronai (virti)",         category:"Grūdai", kcal:99,  protein:3.4,  fat:0.1,  carbs:21,  units:[{label:"1 porcija (200g)",grams:200}] },
  { id:"udon",       name:"Udon makaronai (virti)",         category:"Grūdai", kcal:105, protein:2.8,  fat:0.3,  carbs:22,  units:[{label:"1 porcija (200g)",grams:200}] },
  { id:"rice_nood",  name:"Ryžių makaronai (virti)",        category:"Grūdai", kcal:109, protein:1.8,  fat:0.2,  carbs:25,  units:[{label:"1 porcija (200g)",grams:200}] },
  { id:"bread_rye",  name:"Ruginė duona",                   category:"Grūdai", kcal:259, protein:8.5,  fat:3.3,  carbs:48,  units:[{label:"1 riekelė (30g)",grams:30},{label:"2 riekelės",grams:60}] },
  { id:"bread_dark", name:"Juoda duona (lietuviška)",       category:"Grūdai", kcal:229, protein:7.9,  fat:1.3,  carbs:47,  units:[{label:"1 riekelė (35g)",grams:35},{label:"2 riekelės",grams:70}] },
  { id:"bread_wh",   name:"Balta duona",                    category:"Grūdai", kcal:265, protein:9,    fat:3.2,  carbs:49,  units:[{label:"1 riekelė (30g)",grams:30},{label:"2 riekelės",grams:60}] },
  { id:"bread_wht",  name:"Duona iš visų grūdų",            category:"Grūdai", kcal:247, protein:13,   fat:3.4,  carbs:41,  units:[{label:"1 riekelė (35g)",grams:35},{label:"2 riekelės",grams:70}] },
  { id:"buckwheat",  name:"Grikiai (virti)",                category:"Grūdai", kcal:92,  protein:3.4,  fat:0.6,  carbs:20,  units:[{label:"½ puodelio (100g)",grams:100},{label:"1 puodelis (200g)",grams:200}] },
  { id:"millet",     name:"Soros (virtos)",                 category:"Grūdai", kcal:119, protein:3.5,  fat:1,    carbs:23,  units:[{label:"½ puodelio (100g)",grams:100}] },
  { id:"quinoa",     name:"Kvietinukai / Kvinoja (virti)",  category:"Grūdai", kcal:120, protein:4.4,  fat:1.9,  carbs:22,  units:[{label:"½ puodelio (100g)",grams:100},{label:"1 puodelis (200g)",grams:200}] },
  { id:"couscous",   name:"Kuskusas (virti)",               category:"Grūdai", kcal:112, protein:3.8,  fat:0.2,  carbs:23,  units:[{label:"½ puodelio (100g)",grams:100}] },
  { id:"barley",     name:"Miežiai perliniai (virti)",       category:"Grūdai", kcal:123, protein:2.3,  fat:0.4,  carbs:28,  units:[{label:"½ puodelio (100g)",grams:100}] },
  { id:"spelt",      name:"Spelta (virta)",                  category:"Grūdai", kcal:127, protein:5.5,  fat:1,    carbs:26,  units:[{label:"½ puodelio (100g)",grams:100}] },
  { id:"amaranth",   name:"Amarantas (virtas)",             category:"Grūdai", kcal:102, protein:3.8,  fat:1.6,  carbs:18,  units:[{label:"½ puodelio (100g)",grams:100}] },
  { id:"polenta",    name:"Polenta (virta)",                 category:"Grūdai", kcal:70,  protein:1.5,  fat:0.5,  carbs:15,  units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"rye_flakes", name:"Ruginiai dribsniai",             category:"Grūdai", kcal:338, protein:11.7, fat:2.5,  carbs:65,  units:[{label:"½ puodelio (40g)",grams:40}] },
  { id:"flour_wh",   name:"Kvietiniai miltai (balti)",      category:"Grūdai", kcal:364, protein:10.3, fat:1,    carbs:76,  units:[{label:"1 šaukštas (10g)",grams:10},{label:"½ puodelis (60g)",grams:60}] },
  { id:"flour_wwh",  name:"Viso grūdo kvietiniai miltai",   category:"Grūdai", kcal:340, protein:13.7, fat:2.5,  carbs:68,  units:[{label:"1 šaukštas (10g)",grams:10}] },
  { id:"crisp",      name:"Ryžių/kukurūzų traškučiai",      category:"Grūdai", kcal:372, protein:7,    fat:2,    carbs:82,  units:[{label:"1 gabalėlis (10g)",grams:10},{label:"3 gabalėliai",grams:30}] },
  { id:"cornflakes", name:"Cornflakes (dribsniai)",         category:"Grūdai", kcal:375, protein:7.5,  fat:0.9,  carbs:84,  units:[{label:"1 porcija (30g)",grams:30},{label:"2 porcijos",grams:60}] },
  { id:"muesli",     name:"Miuslis (be cukraus)",           category:"Grūdai", kcal:352, protein:11,   fat:7,    carbs:63,  units:[{label:"½ puodelio (50g)",grams:50}] },
  { id:"granola",    name:"Granola (su cukrumi)",           category:"Grūdai", kcal:471, protein:8,    fat:19,   carbs:66,  units:[{label:"½ puodelio (50g)",grams:50}] },

  // ── ANKŠTINIAI ───────────────────────────────────────────────────────────
  { id:"lentils",    name:"Lęšiai (virti)",                 category:"Ankštiniai", kcal:116, protein:9,    fat:0.4,  carbs:20, units:[{label:"½ puodelio (100g)",grams:100},{label:"1 puodelis (200g)",grams:200}] },
  { id:"lentils_r",  name:"Raudonieji lęšiai (virti)",      category:"Ankštiniai", kcal:116, protein:9,    fat:0.5,  carbs:20, units:[{label:"½ puodelio (100g)",grams:100}] },
  { id:"chickpeas",  name:"Avinžirniai (virti)",            category:"Ankštiniai", kcal:164, protein:8.9,  fat:2.6,  carbs:27, units:[{label:"½ puodelio (100g)",grams:100},{label:"1 puodelis (200g)",grams:200}] },
  { id:"beans_blk",  name:"Juodosios pupelės (virtos)",     category:"Ankštiniai", kcal:132, protein:8.9,  fat:0.5,  carbs:24, units:[{label:"½ puodelio (100g)",grams:100}] },
  { id:"beans_wh",   name:"Baltosios pupelės (virtos)",     category:"Ankštiniai", kcal:139, protein:9.7,  fat:0.5,  carbs:25, units:[{label:"½ puodelio (100g)",grams:100}] },
  { id:"beans_kid",  name:"Raudonosios pupelės (virtos)",   category:"Ankštiniai", kcal:127, protein:8.7,  fat:0.5,  carbs:22, units:[{label:"½ puodelio (100g)",grams:100}] },
  { id:"peas_split", name:"Žirniai džiovinti (virti)",      category:"Ankštiniai", kcal:118, protein:8.3,  fat:0.4,  carbs:21, units:[{label:"½ puodelio (100g)",grams:100}] },
  { id:"mung",       name:"Mung pupelės (virtos)",          category:"Ankštiniai", kcal:105, protein:7.1,  fat:0.4,  carbs:19, units:[{label:"½ puodelio (100g)",grams:100}] },
  { id:"soybeans",   name:"Sojos pupelės (virtos)",         category:"Ankštiniai", kcal:173, protein:16.6, fat:9,    carbs:10, units:[{label:"½ puodelio (100g)",grams:100}] },
  { id:"edamame",    name:"Edamamė (virta)",                category:"Ankštiniai", kcal:122, protein:11,   fat:5.2,  carbs:8.9, units:[{label:"½ puodelio (80g)",grams:80}] },
  { id:"tofu",       name:"Tofu (kietas)",                  category:"Ankštiniai", kcal:76,  protein:8,    fat:4.2,  carbs:1.9, units:[{label:"½ bloko (140g)",grams:140}] },
  { id:"tofu_firm",  name:"Tofu tvirtas (keptas)",          category:"Ankštiniai", kcal:144, protein:15.6, fat:8.7,  carbs:2.9, units:[{label:"1 porcija (100g)",grams:100}] },
  { id:"tempeh",     name:"Tempeh",                         category:"Ankštiniai", kcal:193, protein:19,   fat:11,   carbs:9.4, units:[{label:"½ bloko (85g)",grams:85}] },
  { id:"hummus",     name:"Hummusas",                       category:"Ankštiniai", kcal:177, protein:7.9,  fat:9.6,  carbs:20, units:[{label:"2 šaukštai (30g)",grams:30},{label:"4 šaukštai",grams:60}] },
  { id:"soy_milk",   name:"Sojos pienas (be cukraus)",      category:"Ankštiniai", kcal:43,  protein:3,    fat:2,    carbs:3.5, units:[{label:"1 stiklinė (200ml)",grams:200}] },

  // ── DARŽOVĖS ─────────────────────────────────────────────────────────────
  { id:"broccoli",   name:"Brokoliai (virti)",              category:"Daržovės", kcal:35,  protein:2.4,  fat:0.4,  carbs:7.2, units:[{label:"1 porcija (150g)",grams:150},{label:"½ porcija",grams:75}] },
  { id:"caulifl",    name:"Žiediniai kopūstai (virti)",     category:"Daržovės", kcal:23,  protein:1.8,  fat:0.3,  carbs:4.1, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"spinach",    name:"Špinatai (švieži)",              category:"Daržovės", kcal:23,  protein:2.9,  fat:0.4,  carbs:3.6, units:[{label:"1 sauja (30g)",grams:30},{label:"didelė sauja (60g)",grams:60}] },
  { id:"spinach_c",  name:"Špinatai (virti)",               category:"Daržovės", kcal:23,  protein:2.9,  fat:0.4,  carbs:3.6, units:[{label:"½ puodelio (100g)",grams:100}] },
  { id:"kale",       name:"Lapiniai kopūstai (kale)",       category:"Daržovės", kcal:49,  protein:4.3,  fat:0.9,  carbs:9,   units:[{label:"1 sauja (30g)",grams:30},{label:"1 porcija (80g)",grams:80}] },
  { id:"carrot",     name:"Morkos",                         category:"Daržovės", kcal:41,  protein:0.9,  fat:0.2,  carbs:10,  units:[{label:"1 vidutin. (80g)",grams:80},{label:"2 vnt",grams:160}] },
  { id:"tomato",     name:"Pomidoras",                      category:"Daržovės", kcal:18,  protein:0.9,  fat:0.2,  carbs:3.9, units:[{label:"1 vidutin. (120g)",grams:120},{label:"2 vnt",grams:240}] },
  { id:"tom_cherry", name:"Vyšniniai pomidorai",            category:"Daržovės", kcal:18,  protein:0.9,  fat:0.2,  carbs:3.9, units:[{label:"10 vnt (100g)",grams:100},{label:"20 vnt",grams:200}] },
  { id:"cucumber",   name:"Agurkas",                        category:"Daržovės", kcal:15,  protein:0.7,  fat:0.1,  carbs:3.6, units:[{label:"½ agurko (100g)",grams:100},{label:"1 visas (200g)",grams:200}] },
  { id:"pepper_red", name:"Raudonoji paprika",              category:"Daržovės", kcal:31,  protein:1,    fat:0.3,  carbs:6,   units:[{label:"1 vnt (150g)",grams:150},{label:"½ vnt",grams:75}] },
  { id:"pepper_yel", name:"Geltonoji paprika",              category:"Daržovės", kcal:27,  protein:1,    fat:0.2,  carbs:6.3, units:[{label:"1 vnt (150g)",grams:150}] },
  { id:"pepper_grn", name:"Žalioji paprika",                category:"Daržovės", kcal:20,  protein:0.9,  fat:0.2,  carbs:4.6, units:[{label:"1 vnt (150g)",grams:150}] },
  { id:"onion",      name:"Svogūnas",                       category:"Daržovės", kcal:40,  protein:1.1,  fat:0.1,  carbs:9.3, units:[{label:"1 vidutin. (110g)",grams:110},{label:"½ svogūno",grams:55}] },
  { id:"onion_red",  name:"Raudonasis svogūnas",            category:"Daržovės", kcal:40,  protein:1.1,  fat:0.1,  carbs:9.3, units:[{label:"1 vidutin. (110g)",grams:110}] },
  { id:"spring_on",  name:"Žalieji svogūnai",              category:"Daržovės", kcal:32,  protein:1.8,  fat:0.2,  carbs:7.3, units:[{label:"1 ryšelis (50g)",grams:50}] },
  { id:"garlic",     name:"Česnakas",                       category:"Daržovės", kcal:149, protein:6.4,  fat:0.5,  carbs:33,  units:[{label:"1 skiltelė (5g)",grams:5},{label:"2 skiltelės",grams:10}] },
  { id:"zucchini",   name:"Cukinija (kepta)",               category:"Daržovės", kcal:17,  protein:1.2,  fat:0.3,  carbs:3.1, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"eggplant",   name:"Baklažanas (keptas)",            category:"Daržovės", kcal:35,  protein:0.8,  fat:0.2,  carbs:8.7, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"mushroom",   name:"Pievagrybiai (kepti)",           category:"Daržovės", kcal:29,  protein:1.8,  fat:1.7,  carbs:4.4, units:[{label:"5 vnt (100g)",grams:100},{label:"10 vnt",grams:200}] },
  { id:"lettuce",    name:"Salotos (lapinės)",              category:"Daržovės", kcal:15,  protein:1.4,  fat:0.2,  carbs:2.9, units:[{label:"1 saujelė (30g)",grams:30},{label:"1 didelė porcija (80g)",grams:80}] },
  { id:"potato",     name:"Bulvė (virta)",                  category:"Daržovės", kcal:87,  protein:1.9,  fat:0.1,  carbs:20,  units:[{label:"1 vidutin. (150g)",grams:150},{label:"2 vnt",grams:300}] },
  { id:"potato_bk",  name:"Bulvė (kepta orkaitėje)",        category:"Daržovės", kcal:93,  protein:2.5,  fat:0.1,  carbs:21,  units:[{label:"1 vidutin. (150g)",grams:150}] },
  { id:"sweet_pot",  name:"Saldžioji bulvė (virta)",        category:"Daržovės", kcal:86,  protein:1.6,  fat:0.1,  carbs:20,  units:[{label:"1 vidutin. (150g)",grams:150}] },
  { id:"avocado",    name:"Avokadas",                       category:"Daržovės", kcal:160, protein:2,    fat:15,   carbs:9,   units:[{label:"½ vnt (75g)",grams:75},{label:"1 visas (150g)",grams:150}] },
  { id:"beetroot",   name:"Burokėliai (virti)",             category:"Daržovės", kcal:43,  protein:1.6,  fat:0.2,  carbs:10,  units:[{label:"1 vidutin. (100g)",grams:100}] },
  { id:"cabbage",    name:"Kopūstai (švieži)",              category:"Daržovės", kcal:25,  protein:1.3,  fat:0.1,  carbs:5.8, units:[{label:"1 porcija (100g)",grams:100}] },
  { id:"cabbage_red",name:"Raudonieji kopūstai",            category:"Daržovės", kcal:31,  protein:1.4,  fat:0.2,  carbs:7,   units:[{label:"1 porcija (100g)",grams:100}] },
  { id:"sauerkraut", name:"Rauginti kopūstai",              category:"Daržovės", kcal:19,  protein:0.9,  fat:0.1,  carbs:4.3, units:[{label:"½ puodelis (75g)",grams:75}] },
  { id:"corn",       name:"Kukurūzai (skardinė, nusausintas)", category:"Daržovės", kcal:86, protein:3.2, fat:1.2,  carbs:19,  units:[{label:"½ skardinė (100g)",grams:100}] },
  { id:"peas_frz",   name:"Žirneliai (užšaldyti, virti)",   category:"Daržovės", kcal:69,  protein:5,    fat:0.4,  carbs:12,  units:[{label:"½ puodelio (80g)",grams:80}] },
  { id:"peas_fresh", name:"Žirneliai šviežiai (žali)",      category:"Daržovės", kcal:81,  protein:5.4,  fat:0.4,  carbs:14,  units:[{label:"½ puodelio (80g)",grams:80}] },
  { id:"asparagus",  name:"Šparagai (virti)",               category:"Daržovės", kcal:22,  protein:2.4,  fat:0.2,  carbs:4.1, units:[{label:"5 stiebeliai (100g)",grams:100}] },
  { id:"green_beans",name:"Žaliosios pupelės (virtos)",     category:"Daržovės", kcal:35,  protein:1.8,  fat:0.4,  carbs:7.9, units:[{label:"1 porcija (100g)",grams:100}] },
  { id:"leek",       name:"Poras (virtas)",                 category:"Daržovės", kcal:61,  protein:1.5,  fat:0.3,  carbs:14,  units:[{label:"1 porcija (100g)",grams:100}] },
  { id:"parsnip",    name:"Pastarnokos (virtos)",           category:"Daržovės", kcal:71,  protein:1.3,  fat:0.3,  carbs:17,  units:[{label:"1 porcija (100g)",grams:100}] },
  { id:"turnip",     name:"Ropė (virta)",                   category:"Daržovės", kcal:22,  protein:0.9,  fat:0.1,  carbs:5,   units:[{label:"1 porcija (100g)",grams:100}] },
  { id:"radish",     name:"Ridikėliai (švieži)",            category:"Daržovės", kcal:16,  protein:0.7,  fat:0.1,  carbs:3.4, units:[{label:"5 vnt (50g)",grams:50}] },
  { id:"rucola",     name:"Rucola (rukola)",                category:"Daržovės", kcal:25,  protein:2.6,  fat:0.7,  carbs:3.7, units:[{label:"1 sauja (30g)",grams:30}] },
  { id:"fennel",     name:"Fenkolis (švieži)",              category:"Daržovės", kcal:31,  protein:1.2,  fat:0.2,  carbs:7.3, units:[{label:"1 porcija (100g)",grams:100}] },
  { id:"pumpkin",    name:"Moliūgas (virtas)",              category:"Daržovės", kcal:26,  protein:1,    fat:0.1,  carbs:6.5, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"kohlrabi",   name:"Kaliaropė (žalia)",              category:"Daržovės", kcal:27,  protein:1.7,  fat:0.1,  carbs:6.2, units:[{label:"1 porcija (100g)",grams:100}] },
  { id:"celery",     name:"Salierai (saliero kotai)",       category:"Daržovės", kcal:16,  protein:0.7,  fat:0.2,  carbs:3,   units:[{label:"2 kotai (80g)",grams:80}] },
  { id:"celeriac",   name:"Saliero šaknis (žalia)",         category:"Daržovės", kcal:42,  protein:1.5,  fat:0.3,  carbs:9.2, units:[{label:"1 porcija (100g)",grams:100}] },
  { id:"chard",      name:"Mangoldas (virti)",              category:"Daržovės", kcal:20,  protein:1.9,  fat:0.1,  carbs:4,   units:[{label:"1 porcija (100g)",grams:100}] },
  { id:"pak_choi",   name:"Pak choi (virti)",               category:"Daržovės", kcal:13,  protein:1.6,  fat:0.2,  carbs:1.8, units:[{label:"1 porcija (100g)",grams:100}] },
  { id:"watercress", name:"Vandenkraitis (švieži)",         category:"Daržovės", kcal:11,  protein:2.3,  fat:0.1,  carbs:1.3, units:[{label:"1 sauja (30g)",grams:30}] },
  { id:"okra",       name:"Okra (virta)",                   category:"Daržovės", kcal:33,  protein:1.9,  fat:0.2,  carbs:7.5, units:[{label:"1 porcija (100g)",grams:100}] },
  { id:"artichoke",  name:"Artišokas (virtas)",             category:"Daržovės", kcal:53,  protein:2.9,  fat:0.2,  carbs:12,  units:[{label:"1 vnt (120g)",grams:120}] },
  { id:"bamboo",     name:"Bambukiniai ūgliai (konservuoti)", category:"Daržovės", kcal:27, protein:2.7, fat:0.5,  carbs:5.2, units:[{label:"½ skardinė (100g)",grams:100}] },
  { id:"ginger",     name:"Imbiero šaknis (šviežia)",       category:"Daržovės", kcal:80,  protein:1.8,  fat:0.8,  carbs:18,  units:[{label:"1 šaukštelis (5g)",grams:5},{label:"1 šaukštas (15g)",grams:15}] },
  { id:"parsley",    name:"Petražolės (švieži)",            category:"Daržovės", kcal:36,  protein:3,    fat:0.8,  carbs:6.3, units:[{label:"1 ryšelis (20g)",grams:20}] },
  { id:"dill",       name:"Krapai (švieži)",                category:"Daržovės", kcal:43,  protein:3.5,  fat:1.1,  carbs:7,   units:[{label:"1 ryšelis (20g)",grams:20}] },
  { id:"basil",      name:"Bazilikas (švieži)",             category:"Daržovės", kcal:22,  protein:3.2,  fat:0.6,  carbs:2.7, units:[{label:"1 saujelė (10g)",grams:10}] },
  { id:"mushroom_p", name:"Baravykai (kepti)",              category:"Daržovės", kcal:29,  protein:2.5,  fat:0.4,  carbs:5,   units:[{label:"1 porcija (100g)",grams:100}] },
  { id:"mushroom_ch",name:"Voveraites (keptos)",            category:"Daržovės", kcal:27,  protein:1.9,  fat:0.5,  carbs:4.5, units:[{label:"1 porcija (100g)",grams:100}] },
  { id:"mushroom_sh",name:"Šiitake (virtos)",               category:"Daržovės", kcal:34,  protein:2.2,  fat:0.5,  carbs:7,   units:[{label:"5 vnt (80g)",grams:80}] },
  { id:"mushroom_oy",name:"Austrių grybai (kepti)",         category:"Daržovės", kcal:33,  protein:3.3,  fat:0.4,  carbs:6.1, units:[{label:"1 porcija (100g)",grams:100}] },

  // ── VAISIAI ──────────────────────────────────────────────────────────────
  { id:"banana",     name:"Bananas",                        category:"Vaisiai", kcal:89,  protein:1.1,  fat:0.3,  carbs:23,  units:[{label:"1 mažas (90g)",grams:90},{label:"1 vidutin. (120g)",grams:120},{label:"1 didelis (150g)",grams:150}] },
  { id:"apple",      name:"Obuolys",                        category:"Vaisiai", kcal:52,  protein:0.3,  fat:0.2,  carbs:14,  units:[{label:"1 mažas (120g)",grams:120},{label:"1 vidutin. (150g)",grams:150},{label:"1 didelis (200g)",grams:200}] },
  { id:"orange",     name:"Apelsinas",                      category:"Vaisiai", kcal:47,  protein:0.9,  fat:0.1,  carbs:12,  units:[{label:"1 vnt (150g)",grams:150},{label:"2 vnt",grams:300}] },
  { id:"pear",       name:"Kriaušė",                        category:"Vaisiai", kcal:57,  protein:0.4,  fat:0.1,  carbs:15,  units:[{label:"1 vidutin. (150g)",grams:150}] },
  { id:"berries",    name:"Uogos (mišrainė)",               category:"Vaisiai", kcal:57,  protein:0.7,  fat:0.5,  carbs:14,  units:[{label:"½ puodelio (75g)",grams:75},{label:"1 puodelis (150g)",grams:150}] },
  { id:"strawberry", name:"Braškės",                        category:"Vaisiai", kcal:32,  protein:0.7,  fat:0.3,  carbs:7.7, units:[{label:"10 vnt (100g)",grams:100},{label:"20 vnt",grams:200}] },
  { id:"blueberry",  name:"Mėlynės",                        category:"Vaisiai", kcal:57,  protein:0.7,  fat:0.3,  carbs:14,  units:[{label:"½ puodelio (75g)",grams:75},{label:"1 puodelis (150g)",grams:150}] },
  { id:"grape",      name:"Vynuogės",                       category:"Vaisiai", kcal:67,  protein:0.6,  fat:0.4,  carbs:17,  units:[{label:"sauja (80g)",grams:80},{label:"didelė sauja (150g)",grams:150}] },
  { id:"mango",      name:"Mangas",                         category:"Vaisiai", kcal:60,  protein:0.8,  fat:0.4,  carbs:15,  units:[{label:"½ vnt (100g)",grams:100},{label:"1 visas (200g)",grams:200}] },
  { id:"kiwi",       name:"Kivis",                          category:"Vaisiai", kcal:61,  protein:1.1,  fat:0.5,  carbs:15,  units:[{label:"1 vnt (70g)",grams:70},{label:"2 vnt",grams:140}] },
  { id:"pineapple",  name:"Ananasas (šviežias)",            category:"Vaisiai", kcal:50,  protein:0.5,  fat:0.1,  carbs:13,  units:[{label:"1 riekelė (80g)",grams:80},{label:"2 riekelės",grams:160}] },
  { id:"watermelon", name:"Arbūzas",                        category:"Vaisiai", kcal:30,  protein:0.6,  fat:0.2,  carbs:7.6, units:[{label:"1 porcija (200g)",grams:200},{label:"2 porcijos",grams:400}] },
  { id:"dates",      name:"Datulės (džiovintos)",           category:"Vaisiai", kcal:277, protein:1.8,  fat:0.2,  carbs:75,  units:[{label:"2 vnt (20g)",grams:20},{label:"4 vnt",grams:40}] },
  { id:"plum",       name:"Slyvos",                         category:"Vaisiai", kcal:46,  protein:0.7,  fat:0.3,  carbs:11,  units:[{label:"2 vnt (100g)",grams:100},{label:"4 vnt",grams:200}] },
  { id:"peach",      name:"Persikai",                       category:"Vaisiai", kcal:39,  protein:0.9,  fat:0.3,  carbs:10,  units:[{label:"1 vnt (130g)",grams:130}] },
  { id:"nectarine",  name:"Nektarinai",                     category:"Vaisiai", kcal:44,  protein:1.1,  fat:0.3,  carbs:11,  units:[{label:"1 vnt (130g)",grams:130}] },
  { id:"cherry",     name:"Vyšnios / Trešnės",              category:"Vaisiai", kcal:63,  protein:1.1,  fat:0.2,  carbs:16,  units:[{label:"sauja (80g)",grams:80},{label:"didelė sauja (150g)",grams:150}] },
  { id:"apricot",    name:"Abrikosai (švieži)",             category:"Vaisiai", kcal:48,  protein:1.4,  fat:0.4,  carbs:11,  units:[{label:"2 vnt (80g)",grams:80}] },
  { id:"apricot_d",  name:"Abrikosai (džiovinti)",          category:"Vaisiai", kcal:241, protein:3.4,  fat:0.5,  carbs:63,  units:[{label:"5 vnt (40g)",grams:40}] },
  { id:"gooseberry", name:"Agrastai",                       category:"Vaisiai", kcal:44,  protein:0.9,  fat:0.6,  carbs:10,  units:[{label:"sauja (80g)",grams:80}] },
  { id:"blackcurr",  name:"Juodieji serbentai",             category:"Vaisiai", kcal:63,  protein:1.4,  fat:0.4,  carbs:15,  units:[{label:"sauja (80g)",grams:80}] },
  { id:"redcurr",    name:"Raudonieji serbentai",           category:"Vaisiai", kcal:56,  protein:1.4,  fat:0.2,  carbs:14,  units:[{label:"sauja (80g)",grams:80}] },
  { id:"raspberry",  name:"Avietes",                        category:"Vaisiai", kcal:52,  protein:1.2,  fat:0.7,  carbs:12,  units:[{label:"½ puodelis (75g)",grams:75}] },
  { id:"blackberry", name:"Gervuogės",                      category:"Vaisiai", kcal:43,  protein:1.4,  fat:0.5,  carbs:10,  units:[{label:"½ puodelis (75g)",grams:75}] },
  { id:"cranberry",  name:"Spanguolės (šviežios)",          category:"Vaisiai", kcal:46,  protein:0.4,  fat:0.1,  carbs:12,  units:[{label:"½ puodelis (75g)",grams:75}] },
  { id:"lingonb",    name:"Bruknės",                        category:"Vaisiai", kcal:46,  protein:0.6,  fat:0.4,  carbs:12,  units:[{label:"sauja (75g)",grams:75}] },
  { id:"chokeberry", name:"Aronijos (šermukšniai juodieji)", category:"Vaisiai", kcal:47, protein:1.4,  fat:0.5,  carbs:9.6, units:[{label:"sauja (75g)",grams:75}] },
  { id:"grapefruit", name:"Greipfrutas",                    category:"Vaisiai", kcal:42,  protein:0.8,  fat:0.1,  carbs:11,  units:[{label:"½ vnt (120g)",grams:120},{label:"1 visas (240g)",grams:240}] },
  { id:"lemon",      name:"Citrina (minkštimas)",           category:"Vaisiai", kcal:29,  protein:1.1,  fat:0.3,  carbs:9,   units:[{label:"½ citrinos (40g)",grams:40}] },
  { id:"mandarin",   name:"Mandarinas",                     category:"Vaisiai", kcal:53,  protein:0.8,  fat:0.3,  carbs:13,  units:[{label:"1 vnt (70g)",grams:70},{label:"2 vnt",grams:140}] },
  { id:"pomegran",   name:"Granatas (sėklos)",              category:"Vaisiai", kcal:83,  protein:1.7,  fat:1.2,  carbs:19,  units:[{label:"½ granato (90g)",grams:90}] },
  { id:"fig_fresh",  name:"Figai (švieži)",                 category:"Vaisiai", kcal:74,  protein:0.7,  fat:0.3,  carbs:19,  units:[{label:"2 vnt (80g)",grams:80}] },
  { id:"fig_dried",  name:"Figai (džiovinti)",              category:"Vaisiai", kcal:249, protein:3.3,  fat:0.9,  carbs:64,  units:[{label:"2 vnt (30g)",grams:30}] },
  { id:"papaya",     name:"Papaja",                         category:"Vaisiai", kcal:43,  protein:0.5,  fat:0.3,  carbs:11,  units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"passionfr",  name:"Marakujos",                      category:"Vaisiai", kcal:97,  protein:2.2,  fat:0.7,  carbs:23,  units:[{label:"2 vnt (50g)",grams:50}] },
  { id:"prunes",     name:"Slyvos džiovintos (čiugai)",     category:"Vaisiai", kcal:240, protein:2.2,  fat:0.4,  carbs:63,  units:[{label:"4 vnt (40g)",grams:40}] },
  { id:"raisins",    name:"Razinos",                        category:"Vaisiai", kcal:299, protein:3.1,  fat:0.5,  carbs:79,  units:[{label:"2 šaukštai (30g)",grams:30}] },

  // ── RIEŠUTAI IR SĖKLOS ───────────────────────────────────────────────────
  { id:"almonds",    name:"Migdolai",                       category:"Riešutai", kcal:579, protein:21,   fat:50,   carbs:22,  units:[{label:"sauja (30g)",grams:30},{label:"2 saujos (60g)",grams:60}] },
  { id:"walnuts",    name:"Graikiniai riešutai",            category:"Riešutai", kcal:654, protein:15,   fat:65,   carbs:14,  units:[{label:"sauja (30g)",grams:30}] },
  { id:"cashews",    name:"Anakardžiai",                    category:"Riešutai", kcal:553, protein:18,   fat:44,   carbs:30,  units:[{label:"sauja (30g)",grams:30}] },
  { id:"pistachios", name:"Pistacijos",                     category:"Riešutai", kcal:562, protein:20,   fat:45.3, carbs:27.5, units:[{label:"sauja (30g)",grams:30}] },
  { id:"hazelnuts",  name:"Lazdyno riešutai",              category:"Riešutai", kcal:628, protein:15,   fat:61,   carbs:17,  units:[{label:"sauja (30g)",grams:30}] },
  { id:"pecans",     name:"Pekano riešutai",               category:"Riešutai", kcal:691, protein:9.2,  fat:72,   carbs:14,  units:[{label:"sauja (30g)",grams:30}] },
  { id:"brazil",     name:"Braziliniai riešutai",          category:"Riešutai", kcal:659, protein:14.3, fat:67.1, carbs:12,  units:[{label:"3 vnt (20g)",grams:20}] },
  { id:"peanuts",    name:"Žemės riešutai (žali)",         category:"Riešutai", kcal:567, protein:25.8, fat:49.2, carbs:16.1, units:[{label:"sauja (30g)",grams:30}] },
  { id:"pb",         name:"Žemės riešutų sviestas",        category:"Riešutai", kcal:588, protein:25,   fat:50,   carbs:20,  units:[{label:"1 šaukštas (16g)",grams:16},{label:"2 šaukštai",grams:32}] },
  { id:"almond_b",   name:"Migdolų sviestas",              category:"Riešutai", kcal:614, protein:21,   fat:56,   carbs:19,  units:[{label:"1 šaukštas (16g)",grams:16},{label:"2 šaukštai",grams:32}] },
  { id:"chia",       name:"Čia sėklos",                    category:"Riešutai", kcal:486, protein:17,   fat:31,   carbs:42,  units:[{label:"1 šaukštas (15g)",grams:15},{label:"2 šaukštai",grams:30}] },
  { id:"flax",       name:"Linų sėklos (maltos)",          category:"Riešutai", kcal:534, protein:18,   fat:42,   carbs:29,  units:[{label:"1 šaukštas (10g)",grams:10}] },
  { id:"sunflower",  name:"Saulėgrąžų sėklos",             category:"Riešutai", kcal:584, protein:21,   fat:51,   carbs:20,  units:[{label:"sauja (30g)",grams:30}] },
  { id:"pumpkin_s",  name:"Moliūgų sėklos",                category:"Riešutai", kcal:559, protein:30,   fat:49,   carbs:11,  units:[{label:"sauja (30g)",grams:30}] },
  { id:"sesame",     name:"Sezamo sėklos",                 category:"Riešutai", kcal:573, protein:17.7, fat:49.7, carbs:23.4, units:[{label:"1 šaukštas (10g)",grams:10}] },
  { id:"hemp",       name:"Kanapių sėklos",                category:"Riešutai", kcal:553, protein:31.6, fat:48.8, carbs:8.7, units:[{label:"1 šaukštas (10g)",grams:10}] },
  { id:"poppy",      name:"Aguonos",                        category:"Riešutai", kcal:525, protein:17.9, fat:41.6, carbs:28.1, units:[{label:"1 šaukštas (10g)",grams:10}] },
  { id:"coconut_d",  name:"Kokoso drožlės (džiovintos)",   category:"Riešutai", kcal:660, protein:6.9,  fat:64,   carbs:23.7, units:[{label:"2 šaukštai (20g)",grams:20}] },

  // ── RIEBALAI IR ALIEJAI ──────────────────────────────────────────────────
  { id:"olive_oil",  name:"Alyvuogių aliejus",              category:"Riebalai", kcal:884, protein:0, fat:100, carbs:0, units:[{label:"1 šaukštelis (5ml)",grams:5},{label:"1 šaukštas (15ml)",grams:15}] },
  { id:"sunfl_oil",  name:"Saulėgrąžų aliejus",             category:"Riebalai", kcal:884, protein:0, fat:100, carbs:0, units:[{label:"1 šaukštelis (5ml)",grams:5},{label:"1 šaukštas (15ml)",grams:15}] },
  { id:"rapeseed",   name:"Rapsų aliejus",                  category:"Riebalai", kcal:884, protein:0, fat:100, carbs:0, units:[{label:"1 šaukštelis (5ml)",grams:5},{label:"1 šaukštas (15ml)",grams:15}] },
  { id:"coco_oil",   name:"Kokosų aliejus",                 category:"Riebalai", kcal:862, protein:0, fat:100, carbs:0, units:[{label:"1 šaukštelis (5g)",grams:5},{label:"1 šaukštas (15g)",grams:15}] },
  { id:"avocado_oil",name:"Avokadų aliejus",                category:"Riebalai", kcal:884, protein:0, fat:100, carbs:0, units:[{label:"1 šaukštelis (5ml)",grams:5},{label:"1 šaukštas (15ml)",grams:15}] },
  { id:"flax_oil",   name:"Linų sėmenų aliejus",            category:"Riebalai", kcal:884, protein:0, fat:100, carbs:0, units:[{label:"1 šaukštelis (5ml)",grams:5}] },
  { id:"ghee",       name:"Ghee (lydytas sviestas)",        category:"Riebalai", kcal:900, protein:0, fat:100, carbs:0, units:[{label:"1 šaukštelis (5g)",grams:5},{label:"1 šaukštas (15g)",grams:15}] },
  { id:"margarine",  name:"Margarinas",                     category:"Riebalai", kcal:717, protein:0.2, fat:80, carbs:0.7, units:[{label:"1 šaukštelis (5g)",grams:5},{label:"1 šaukštas (15g)",grams:15}] },

  // ── GĖRIMAI ──────────────────────────────────────────────────────────────
  { id:"prot_wh",    name:"Baltymų kokteilius (whey)",      category:"Gėrimai", kcal:120, protein:25,   fat:2,    carbs:5,   units:[{label:"1 porcija (300ml)",grams:300}] },
  { id:"coffee_bl",  name:"Juoda kava",                     category:"Gėrimai", kcal:2,   protein:0.3,  fat:0,    carbs:0,   units:[{label:"1 puodelis (200ml)",grams:200}] },
  { id:"coffee_lat", name:"Latte (pieno kava)",             category:"Gėrimai", kcal:61,  protein:3.3,  fat:2.4,  carbs:7.2, units:[{label:"1 puodelis (300ml)",grams:300}] },
  { id:"coffee_cap", name:"Kapučinas",                      category:"Gėrimai", kcal:78,  protein:4.2,  fat:3.6,  carbs:7,   units:[{label:"1 puodelis (200ml)",grams:200}] },
  { id:"espresso",   name:"Espresso",                       category:"Gėrimai", kcal:6,   protein:0.3,  fat:0.2,  carbs:1,   units:[{label:"1 shot (30ml)",grams:30}] },
  { id:"green_tea",  name:"Žalioji arbata",                 category:"Gėrimai", kcal:1,   protein:0.2,  fat:0,    carbs:0.2, units:[{label:"1 puodelis (200ml)",grams:200}] },
  { id:"black_tea",  name:"Juodoji arbata",                 category:"Gėrimai", kcal:1,   protein:0.1,  fat:0,    carbs:0.3, units:[{label:"1 puodelis (200ml)",grams:200}] },
  { id:"herb_tea",   name:"Žolelių arbata",                 category:"Gėrimai", kcal:2,   protein:0,    fat:0,    carbs:0.5, units:[{label:"1 puodelis (200ml)",grams:200}] },
  { id:"oat_milk",   name:"Avižų pienas",                   category:"Gėrimai", kcal:46,  protein:1,    fat:1.5,  carbs:7,   units:[{label:"1 stiklinė (200ml)",grams:200}] },
  { id:"alm_milk",   name:"Migdolų pienas (be cukraus)",    category:"Gėrimai", kcal:17,  protein:0.6,  fat:1.4,  carbs:0.3, units:[{label:"1 stiklinė (200ml)",grams:200}] },
  { id:"oj",         name:"Apelsinų sultys (šviežios)",     category:"Gėrimai", kcal:45,  protein:0.7,  fat:0.2,  carbs:10,  units:[{label:"1 stiklinė (200ml)",grams:200}] },
  { id:"apple_juice",name:"Obuolių sultys (be cukraus)",    category:"Gėrimai", kcal:46,  protein:0.1,  fat:0.1,  carbs:11.3, units:[{label:"1 stiklinė (200ml)",grams:200}] },
  { id:"tom_juice",  name:"Pomidorų sultys",                category:"Gėrimai", kcal:17,  protein:0.8,  fat:0.1,  carbs:4,   units:[{label:"1 stiklinė (200ml)",grams:200}] },
  { id:"carrot_j",   name:"Morkų sultys",                   category:"Gėrimai", kcal:40,  protein:0.9,  fat:0.2,  carbs:9.3, units:[{label:"1 stiklinė (200ml)",grams:200}] },
  { id:"cherry_j",   name:"Vyšnių sultys",                  category:"Gėrimai", kcal:56,  protein:0.7,  fat:0.3,  carbs:13,  units:[{label:"1 stiklinė (200ml)",grams:200}] },
  { id:"pomegr_j",   name:"Granatų sultys",                 category:"Gėrimai", kcal:54,  protein:0.2,  fat:0.3,  carbs:13.4, units:[{label:"1 stiklinė (200ml)",grams:200}] },
  { id:"coconut_w",  name:"Kokoso vanduo",                  category:"Gėrimai", kcal:19,  protein:0.7,  fat:0.2,  carbs:3.7, units:[{label:"1 stiklinė (200ml)",grams:200}] },
  { id:"kombucha",   name:"Kombucha",                       category:"Gėrimai", kcal:13,  protein:0,    fat:0,    carbs:3,   units:[{label:"1 buteliukas (250ml)",grams:250}] },
  { id:"kvass",      name:"Gira",                           category:"Gėrimai", kcal:27,  protein:0.2,  fat:0,    carbs:6.5, units:[{label:"1 stiklinė (250ml)",grams:250}] },
  { id:"cocoa_hot",  name:"Kakava (karšta, su pienu)",      category:"Gėrimai", kcal:81,  protein:4.1,  fat:3.3,  carbs:8.7, units:[{label:"1 puodelis (200ml)",grams:200}] },
  { id:"isotonic",   name:"Sportinis gėrimas (izotoninis)", category:"Gėrimai", kcal:23,  protein:0,    fat:0,    carbs:6,   units:[{label:"1 buteliukas (500ml)",grams:500}] },

  // ── PADAŽAI IR PRIESKONIAI ────────────────────────────────────────────────
  { id:"ketchup",    name:"Kečupas",                        category:"Padažai", kcal:101, protein:1.4,  fat:0.1,  carbs:26,  units:[{label:"1 šaukštas (17g)",grams:17}] },
  { id:"mustard",    name:"Garstyčios",                     category:"Padažai", kcal:66,  protein:4.4,  fat:3.5,  carbs:5.8, units:[{label:"1 šaukštelis (5g)",grams:5}] },
  { id:"mayo",       name:"Majonezas",                      category:"Padažai", kcal:680, protein:1,    fat:75,   carbs:1,   units:[{label:"1 šaukštas (15g)",grams:15}] },
  { id:"mayo_lt",    name:"Majonezas lengvas",              category:"Padažai", kcal:292, protein:1,    fat:30,   carbs:3,   units:[{label:"1 šaukštas (15g)",grams:15}] },
  { id:"soysauce",   name:"Sojos padažas",                  category:"Padažai", kcal:53,  protein:8.1,  fat:0.1,  carbs:4.9, units:[{label:"1 šaukštas (15ml)",grams:15}] },
  { id:"honey",      name:"Medus",                          category:"Padažai", kcal:304, protein:0.3,  fat:0,    carbs:82,  units:[{label:"1 šaukštelis (7g)",grams:7},{label:"1 šaukštas (21g)",grams:21}] },
  { id:"maple",      name:"Klevų sirupas",                  category:"Padažai", kcal:260, protein:0.1,  fat:0.1,  carbs:67,  units:[{label:"1 šaukštas (20ml)",grams:20}] },
  { id:"agave",      name:"Agavų sirupas",                  category:"Padažai", kcal:310, protein:0.1,  fat:0.3,  carbs:76,  units:[{label:"1 šaukštas (20ml)",grams:20}] },
  { id:"tahini",     name:"Tahini (sezamo pasta)",          category:"Padažai", kcal:595, protein:17,   fat:53,   carbs:21,  units:[{label:"1 šaukštas (15g)",grams:15}] },
  { id:"pesto",      name:"Pesto padažas",                  category:"Padažai", kcal:376, protein:6,    fat:35,   carbs:9,   units:[{label:"1 šaukštas (20g)",grams:20}] },
  { id:"bbq_sauce",  name:"BBQ padažas",                    category:"Padažai", kcal:172, protein:1,    fat:0.4,  carbs:41,  units:[{label:"1 šaukštas (17g)",grams:17}] },
  { id:"ranch",      name:"Ranch padažas",                  category:"Padažai", kcal:522, protein:1.3,  fat:55,   carbs:5.1, units:[{label:"2 šaukštai (30g)",grams:30}] },
  { id:"sriracha",   name:"Sriracha",                       category:"Padažai", kcal:93,  protein:1.5,  fat:3,    carbs:16,  units:[{label:"1 šaukštelis (5g)",grams:5}] },
  { id:"teriyaki",   name:"Teriyaki padažas",               category:"Padažai", kcal:89,  protein:6.4,  fat:0.1,  carbs:16.4, units:[{label:"1 šaukštas (15ml)",grams:15}] },
  { id:"fish_sauce", name:"Žuvinis padažas",                category:"Padažai", kcal:35,  protein:5.1,  fat:0,    carbs:3.6, units:[{label:"1 šaukštelis (5ml)",grams:5}] },
  { id:"balsamic",   name:"Balzaminis actas",               category:"Padažai", kcal:88,  protein:0.5,  fat:0,    carbs:17,  units:[{label:"1 šaukštas (15ml)",grams:15}] },
  { id:"tom_paste",  name:"Pomidorų pasta",                 category:"Padažai", kcal:82,  protein:4.3,  fat:0.5,  carbs:19,  units:[{label:"1 šaukštas (15g)",grams:15},{label:"2 šaukštai",grams:30}] },
  { id:"tom_sauce",  name:"Pomidorų padažas (iš skardinės)", category:"Padažai", kcal:29, protein:1.2,  fat:0.2,  carbs:7,   units:[{label:"½ stiklinė (125ml)",grams:125}] },
  { id:"coconut_m",  name:"Kokosų pienas (konservuotas)",   category:"Padažai", kcal:197, protein:2,    fat:21,   carbs:2.8, units:[{label:"¼ skardinė (100ml)",grams:100}] },
  { id:"hoisin",     name:"Hoisin padažas",                 category:"Padažai", kcal:220, protein:3.7,  fat:3.5,  carbs:44,  units:[{label:"1 šaukštas (17g)",grams:17}] },
  { id:"miso",       name:"Miso pasta",                     category:"Padažai", kcal:199, protein:12,   fat:6,    carbs:27,  units:[{label:"1 šaukštas (17g)",grams:17}] },
  { id:"nutella",    name:"Nutella",                        category:"Padažai", kcal:539, protein:6.3,  fat:30.9, carbs:57.5, units:[{label:"1 šaukštas (15g)",grams:15}] },
  { id:"sugar_wh",   name:"Cukrus baltas",                  category:"Padažai", kcal:387, protein:0,    fat:0,    carbs:100, units:[{label:"1 šaukštelis (4g)",grams:4},{label:"1 šaukštas (12g)",grams:12}] },
  { id:"sugar_br",   name:"Rudasis cukrus",                 category:"Padažai", kcal:380, protein:0.1,  fat:0,    carbs:98,  units:[{label:"1 šaukštelis (4g)",grams:4}] },
];

// ── PAPILDOMI PRODUKTAI ───────────────────────────────────────────────────────
const EXTRA_FOODS = [
  // Kepykla
  { id:"bagel",      name:"Beigelis (paprastas)",           category:"Kepykla", kcal:272, protein:10.6, fat:1.8,  carbs:53,  units:[{label:"1 mažas (70g)",grams:70},{label:"1 didelis (105g)",grams:105}] },
  { id:"bagel_wh",   name:"Beigelis (viso grūdo)",          category:"Kepykla", kcal:245, protein:11,   fat:2,    carbs:48,  units:[{label:"1 vnt (105g)",grams:105}] },
  { id:"croissant",  name:"Kruasanas",                      category:"Kepykla", kcal:406, protein:8.2,  fat:21,   carbs:46,  units:[{label:"1 mažas (50g)",grams:50},{label:"1 didelis (80g)",grams:80}] },
  { id:"muffin_bl",  name:"Muffinas (su mėlynėmis)",        category:"Kepykla", kcal:377, protein:5.7,  fat:14,   carbs:57,  units:[{label:"1 vnt (113g)",grams:113}] },
  { id:"pita",       name:"Pita duona",                     category:"Kepykla", kcal:275, protein:9.1,  fat:1.2,  carbs:56,  units:[{label:"1 vnt (60g)",grams:60}] },
  { id:"tortilla_wh",name:"Tortila (kvietinė)",             category:"Kepykla", kcal:312, protein:8.5,  fat:7.7,  carbs:51,  units:[{label:"1 maža (30g)",grams:30},{label:"1 didelė (65g)",grams:65}] },
  { id:"tortilla_co",name:"Tortila (kukurūzų)",             category:"Kepykla", kcal:218, protein:5.7,  fat:3.2,  carbs:46,  units:[{label:"1 vnt (26g)",grams:26}] },
  { id:"pancake",    name:"Blynai (klasikiniai)",           category:"Kepykla", kcal:227, protein:6.3,  fat:10,   carbs:28,  units:[{label:"1 blynas (40g)",grams:40},{label:"3 blynai",grams:120}] },
  { id:"waffle",     name:"Vafelis",                        category:"Kepykla", kcal:291, protein:7.9,  fat:14,   carbs:37,  units:[{label:"1 vnt (75g)",grams:75}] },
  { id:"rice_cake",  name:"Ryžių pyragaitis",               category:"Kepykla", kcal:387, protein:8,    fat:2.8,  carbs:81,  units:[{label:"1 vnt (9g)",grams:9},{label:"2 vnt",grams:18}] },
  { id:"dinner_roll",name:"Bandelė",                        category:"Kepykla", kcal:298, protein:8.8,  fat:3.7,  carbs:58,  units:[{label:"1 vnt (50g)",grams:50}] },
  { id:"rye_cracker",name:"Ruginiai krekeriai",             category:"Kepykla", kcal:336, protein:9.5,  fat:5,    carbs:65,  units:[{label:"2 vnt (20g)",grams:20}] },
  { id:"gluten_free",name:"Duona be glitimo",               category:"Kepykla", kcal:235, protein:3.5,  fat:4,    carbs:48,  units:[{label:"1 riekelė (35g)",grams:35}] },

  // Užkandžiai
  { id:"prot_bar",   name:"Baltymų batonėlis (vidut.)",     category:"Snacks",  kcal:350, protein:25,   fat:10,   carbs:40,  units:[{label:"1 vnt (60g)",grams:60}] },
  { id:"chips_pot",  name:"Bulvių traškučiai",              category:"Snacks",  kcal:536, protein:7,    fat:35,   carbs:53,  units:[{label:"sauja (30g)",grams:30},{label:"mažas pakelis (50g)",grams:50}] },
  { id:"popcorn",    name:"Spragėsiai (be sviesto)",        category:"Snacks",  kcal:382, protein:12,   fat:4.3,  carbs:78,  units:[{label:"1 puodelis (8g)",grams:8},{label:"3 puodeliai",grams:24}] },
  { id:"dark_choc",  name:"Juodasis šokoladas (70%+)",      category:"Snacks",  kcal:598, protein:7.8,  fat:42,   carbs:46,  units:[{label:"2 plytelės (20g)",grams:20},{label:"4 plytelės",grams:40}] },
  { id:"milk_choc",  name:"Pieninis šokoladas",             category:"Snacks",  kcal:535, protein:7.7,  fat:29,   carbs:60,  units:[{label:"2 plytelės (20g)",grams:20}] },
  { id:"white_choc", name:"Baltasis šokoladas",             category:"Snacks",  kcal:539, protein:5.9,  fat:30.1, carbs:58.8, units:[{label:"2 plytelės (20g)",grams:20}] },
  { id:"dark_choc85",name:"Juodasis šokoladas (85%+)",      category:"Snacks",  kcal:598, protein:8.5,  fat:43,   carbs:45,  units:[{label:"2 plytelės (20g)",grams:20}] },
  { id:"pretzel",    name:"Preceliai",                      category:"Snacks",  kcal:381, protein:9.6,  fat:3.6,  carbs:80,  units:[{label:"sauja (30g)",grams:30}] },
  { id:"granola_bar",name:"Granola batonėlis",              category:"Snacks",  kcal:471, protein:7,    fat:19,   carbs:70,  units:[{label:"1 vnt (47g)",grams:47}] },
  { id:"rice_choc",  name:"Ryžių traškučiai šokolade",      category:"Snacks",  kcal:495, protein:4.5,  fat:22,   carbs:70,  units:[{label:"3 vnt (30g)",grams:30}] },

  // Perdirbta mėsa
  { id:"ham",        name:"Kumpis (virtas)",                category:"Perdirbta mėsa", kcal:145, protein:20,   fat:6.5,  carbs:1.6, units:[{label:"2 riekelės (60g)",grams:60},{label:"4 riekelės",grams:120}] },
  { id:"salami",     name:"Salami",                         category:"Perdirbta mėsa", kcal:425, protein:22,   fat:37,   carbs:1.2, units:[{label:"3 riekelės (30g)",grams:30}] },
  { id:"hotdog",     name:"Dešra (virta)",                  category:"Perdirbta mėsa", kcal:290, protein:11,   fat:26,   carbs:2.7, units:[{label:"1 vnt (52g)",grams:52}] },
  { id:"sausage_br", name:"Dešrelė pusryčiams (kepta)",     category:"Perdirbta mėsa", kcal:301, protein:13,   fat:27,   carbs:2,   units:[{label:"1 vnt (45g)",grams:45},{label:"2 vnt",grams:90}] },
  { id:"skilandis",  name:"Skilandis (lietuviškas)",         category:"Perdirbta mėsa", kcal:350, protein:20,   fat:29,   carbs:0,   units:[{label:"3 riekelės (30g)",grams:30}] },
  { id:"chorizo",    name:"Chorizo",                        category:"Perdirbta mėsa", kcal:455, protein:24.1, fat:38.3, carbs:2.5, units:[{label:"3 riekelės (30g)",grams:30}] },
  { id:"pepperoni",  name:"Pepperoni",                      category:"Perdirbta mėsa", kcal:494, protein:22.7, fat:44,   carbs:0.7, units:[{label:"5 riekelės (28g)",grams:28}] },
  { id:"prosciutto", name:"Prošutas (Prosciutto)",          category:"Perdirbta mėsa", kcal:215, protein:27,   fat:11.6, carbs:0.9, units:[{label:"2 riekelės (30g)",grams:30}] },
  { id:"bresaola",   name:"Bresaola (jautiena džiovinta)",  category:"Perdirbta mėsa", kcal:151, protein:32,   fat:2,    carbs:0.5, units:[{label:"3 riekelės (30g)",grams:30}] },

  // Restoranai / greitas maistas
  { id:"pizza_sl",   name:"Pica (1 gabalėlis, sūrio)",      category:"Restoranai", kcal:285, protein:12,   fat:10,   carbs:36,  units:[{label:"1 gabalėlis (107g)",grams:107},{label:"2 gabalėliai",grams:214}] },
  { id:"burger_p",   name:"Burgerio kotletas (jautiena)",   category:"Restoranai", kcal:295, protein:20,   fat:23,   carbs:0,   units:[{label:"1 kotletas (113g)",grams:113}] },
  { id:"sushi_r",    name:"Sushi ritiniklis (su žuvimi)",   category:"Restoranai", kcal:93,  protein:5,    fat:0.7,  carbs:18,  units:[{label:"1 vnt (28g)",grams:28},{label:"6 vnt",grams:168}] },
  { id:"falafel",    name:"Falafelis (keptas)",             category:"Restoranai", kcal:333, protein:13.3, fat:17.8, carbs:31.8, units:[{label:"3 vnt (90g)",grams:90}] },
  { id:"shawarma",   name:"Šavarma (vištienos, su duona)",  category:"Restoranai", kcal:215, protein:14,   fat:8.5,  carbs:22,  units:[{label:"1 porcija (200g)",grams:200}] },
  { id:"kebab",      name:"Kebabas (jautienos/ėrienos)",    category:"Restoranai", kcal:195, protein:20,   fat:11,   carbs:5,   units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"fish_chips", name:"Žuvis su bulvytėmis",            category:"Restoranai", kcal:235, protein:12,   fat:12,   carbs:22,  units:[{label:"1 porcija (200g)",grams:200}] },

  // Lietuviški patiekalai
  { id:"cepelin",    name:"Cepelinai su mėsa",              category:"Lietuviški patiekalai", kcal:127, protein:6, fat:4,    carbs:18,  units:[{label:"1 vnt (300g)",grams:300}] },
  { id:"kibin",      name:"Kibinas su ėriena",              category:"Lietuviški patiekalai", kcal:305, protein:12, fat:18,  carbs:25,  units:[{label:"1 vnt (150g)",grams:150}] },
  { id:"saltibars",  name:"Šaltibarščiai",                  category:"Lietuviški patiekalai", kcal:52,  protein:2.8, fat:1.8, carbs:6, units:[{label:"1 porcija (300ml)",grams:300}] },
  { id:"borscht",    name:"Barščiai (su jautiena)",         category:"Lietuviški patiekalai", kcal:45,  protein:2.5, fat:1.5, carbs:7, units:[{label:"1 porcija (300ml)",grams:300}] },
  { id:"bulv_kose",  name:"Bulvių košė (su sviestu)",       category:"Lietuviški patiekalai", kcal:94,  protein:2,   fat:3.5, carbs:15, units:[{label:"1 porcija (200g)",grams:200}] },
  { id:"kugelis",    name:"Kugelis",                        category:"Lietuviški patiekalai", kcal:175, protein:7,   fat:9,   carbs:19, units:[{label:"1 gabalėlis (150g)",grams:150}] },
  { id:"varsk_apk",  name:"Varškės apkepas",                category:"Lietuviški patiekalai", kcal:185, protein:10.5, fat:8,  carbs:20, units:[{label:"1 gabalėlis (150g)",grams:150}] },
  { id:"zem_blyn",   name:"Žemaičių blynai",                category:"Lietuviški patiekalai", kcal:165, protein:5,   fat:8,   carbs:20, units:[{label:"1 blynas (100g)",grams:100}] },

  // Sriubos
  { id:"soup_chick", name:"Vištienos sriuba",               category:"Sriubos", kcal:45,  protein:4.5,  fat:1.5,  carbs:4,   units:[{label:"1 porcija (350ml)",grams:350}] },
  { id:"soup_veg",   name:"Daržovių sriuba",                category:"Sriubos", kcal:35,  protein:1.5,  fat:0.5,  carbs:7,   units:[{label:"1 porcija (350ml)",grams:350}] },
  { id:"soup_lent",  name:"Lęšių sriuba",                   category:"Sriubos", kcal:87,  protein:5.4,  fat:1,    carbs:15,  units:[{label:"1 porcija (350ml)",grams:350}] },
  { id:"soup_bean",  name:"Pupelių sriuba",                 category:"Sriubos", kcal:90,  protein:5.5,  fat:1.5,  carbs:15,  units:[{label:"1 porcija (350ml)",grams:350}] },
  { id:"soup_tom",   name:"Pomidorų sriuba (su grietinėle)", category:"Sriubos", kcal:62, protein:1.2,  fat:3.5,  carbs:7,   units:[{label:"1 porcija (350ml)",grams:350}] },
  { id:"soup_mush",  name:"Grybų sriuba",                   category:"Sriubos", kcal:38,  protein:1.8,  fat:1,    carbs:6,   units:[{label:"1 porcija (350ml)",grams:350}] },
  { id:"soup_borscht",name:"Barščiai (burokėlių sriuba)",   category:"Sriubos", kcal:45,  protein:2.5,  fat:1.5,  carbs:7,   units:[{label:"1 porcija (350ml)",grams:350}] },
  { id:"soup_pea",   name:"Žirnių sriuba su rūkyta mėsa",   category:"Sriubos", kcal:98,  protein:6,    fat:2.5,  carbs:14,  units:[{label:"1 porcija (350ml)",grams:350}] },

  // Papildomi pieno produktai
  { id:"prot_yog",   name:"Baltyminis jogurtas (Skyr tipo)", category:"Pieno produktai", kcal:67, protein:11, fat:0.2, carbs:4.5, units:[{label:"1 indelis (150g)",grams:150},{label:"1 didelis (200g)",grams:200}] },
  { id:"ice_cream",  name:"Ledai (vaniliniai)",              category:"Pieno produktai", kcal:207, protein:3.5, fat:11, carbs:24, units:[{label:"1 kaušelis (65g)",grams:65},{label:"2 kaušeliai",grams:130}] },
  { id:"ice_cream_ch",name:"Ledai (šokoladiniai)",           category:"Pieno produktai", kcal:216, protein:3.8, fat:11.5, carbs:26, units:[{label:"1 kaušelis (65g)",grams:65}] },
  { id:"curd_farmer",name:"Ūkio varškė (fermerių)",          category:"Pieno produktai", kcal:98,  protein:11,  fat:4,   carbs:3.8, units:[{label:"½ puodelis (120g)",grams:120}] },

  // Kita
  { id:"olives_bl",  name:"Alyvuogės (juodos)",             category:"Kita", kcal:115, protein:0.8,  fat:10.9, carbs:6.3, units:[{label:"10 vnt (40g)",grams:40}] },
  { id:"olives_gr",  name:"Alyvuogės (žaliosios)",          category:"Kita", kcal:115, protein:0.8,  fat:10.7, carbs:6.3, units:[{label:"10 vnt (40g)",grams:40}] },
  { id:"pickles",    name:"Sūdyti agurkėliai",              category:"Kita", kcal:12,  protein:0.6,  fat:0.2,  carbs:2.6, units:[{label:"1 agurkas (40g)",grams:40}] },
  { id:"pickled_b",  name:"Raugintos burokėliai",           category:"Kita", kcal:31,  protein:1.2,  fat:0.1,  carbs:7,   units:[{label:"2 riekelės (60g)",grams:60}] },
  { id:"sun_tom_dry",name:"Džiovinti pomidorai (be aliejaus)", category:"Kita", kcal:258, protein:14.1, fat:3, carbs:55.8, units:[{label:"5 vnt (30g)",grams:30}] },
  { id:"capers",     name:"Kaparai",                        category:"Kita", kcal:23,  protein:2.4,  fat:0.9,  carbs:4.9, units:[{label:"1 šaukštas (15g)",grams:15}] },
  { id:"toasted_b",  name:"Sausainiai oatmeal",             category:"Kita", kcal:471, protein:7,    fat:19,   carbs:69,  units:[{label:"2 sausainiai (30g)",grams:30}] },
  { id:"corn_ch",    name:"Kukurūzų dribsniai šokolado glaze", category:"Kita", kcal:397, protein:6, fat:5.5, carbs:82, units:[{label:"1 porcija (30g)",grams:30}] },
];

// ── LIETUVIŠKOS IR LIETUVOJE PARDUODAMOS PREKĖS SU BARKODAIS ───────────────
const LT_BRANDED = [

  // ═══ PIENO PRODUKTAI – lietuviški gamintojai ═══

  // Džiugas
  { id:"dziugas_12",  name:"Džiugas brandintas sūris 12 mėn.",   category:"🇱🇹 Lietuviški produktai", kcal:389, protein:26,   fat:31,   carbs:0,   units:[{label:"1 riekelė (30g)",grams:30},{label:"50g",grams:50}] },
  { id:"dziugas_18",  name:"Džiugas brandintas sūris 18 mėn.",   category:"🇱🇹 Lietuviški produktai", kcal:402, protein:28,   fat:32,   carbs:0,   units:[{label:"1 riekelė (30g)",grams:30},{label:"50g",grams:50}] },
  { id:"dziugas_24",  name:"Džiugas senasis sūris 24 mėn.",      category:"🇱🇹 Lietuviški produktai", kcal:405, protein:29,   fat:32.5, carbs:0,   units:[{label:"1 riekelė (30g)",grams:30},{label:"50g",grams:50}] },
  { id:"dziugas_36",  name:"Džiugas ekstra brandintas 36 mėn.",  category:"🇱🇹 Lietuviški produktai", kcal:413, protein:30,   fat:33,   carbs:0,   units:[{label:"1 riekelė (30g)",grams:30}] },

  // Rokiškio
  { id:"rokiskio_sur",name:"Rokiškio sūris 45%",                 category:"🇱🇹 Lietuviški produktai", kcal:356, protein:25,   fat:28,   carbs:0.5, units:[{label:"1 riekelė (30g)",grams:30},{label:"2 riekelės",grams:60}] },
  { id:"rokiskio_v5", name:"Rokiškio varškė 5%",                 category:"🇱🇹 Lietuviški produktai", kcal:103, protein:11,   fat:4.5,  carbs:3.4, units:[{label:"½ puodelis (120g)",grams:120},{label:"1 puodelis (240g)",grams:240}] },
  { id:"rokiskio_v9", name:"Rokiškio varškė 9%",                 category:"🇱🇹 Lietuviški produktai", kcal:174, protein:9,    fat:9,    carbs:3.5, units:[{label:"½ puodelis (120g)",grams:120}] },
  { id:"rokiskio_gr", name:"Rokiškio grietinė 30%",              category:"🇱🇹 Lietuviški produktai", kcal:292, protein:2.5,  fat:30,   carbs:3.5, units:[{label:"1 šaukštas (25g)",grams:25}] },
  { id:"rokiskio_pi", name:"Rokiškio pienas 3,5%",               category:"🇱🇹 Lietuviški produktai", kcal:61,  protein:3.2,  fat:3.5,  carbs:4.8, units:[{label:"1 stiklinė (200ml)",grams:200}] },
  { id:"rokiskio_kef",name:"Rokiškio kefyras 2,5%",              category:"🇱🇹 Lietuviški produktai", kcal:52,  protein:3.2,  fat:2.5,  carbs:4.5, units:[{label:"1 stiklinė (200ml)",grams:200}] },
  { id:"rokiskio_jog",name:"Rokiškio natūralus jogurtas 3,5%",   category:"🇱🇹 Lietuviški produktai", kcal:68,  protein:3.5,  fat:3.5,  carbs:5.2, units:[{label:"1 indelis (180g)",grams:180}] },
  { id:"rokiskio_but",name:"Rokiškio sviestas 82,5%",            category:"🇱🇹 Lietuviški produktai", kcal:741, protein:0.6,  fat:82.5, carbs:0.6, units:[{label:"1 šaukštelis (5g)",grams:5},{label:"1 šaukštas (15g)",grams:15}] },

  // Žemaitijos pienas
  { id:"zem_sur45",   name:"Žemaitijos sūris 45%",               category:"🇱🇹 Lietuviški produktai", kcal:348, protein:24.5, fat:27.5, carbs:0.5, units:[{label:"1 riekelė (30g)",grams:30}] },
  { id:"zem_pienas",  name:"Žemaitijos pienas 2,5%",             category:"🇱🇹 Lietuviški produktai", kcal:47,  protein:3.3,  fat:2.5,  carbs:4.8, units:[{label:"1 stiklinė (200ml)",grams:200}] },
  { id:"zem_sviest",  name:"Žemaitijos sviestas 82%",            category:"🇱🇹 Lietuviški produktai", kcal:738, protein:0.6,  fat:82,   carbs:0.7, units:[{label:"1 šaukštelis (5g)",grams:5},{label:"1 šaukštas (15g)",grams:15}] },
  { id:"zem_griet",   name:"Žemaitijos grietinė 15%",            category:"🇱🇹 Lietuviški produktai", kcal:160, protein:2.8,  fat:15,   carbs:4,   units:[{label:"1 šaukštas (25g)",grams:25}] },

  // Vilkyškių pieninė
  { id:"vilk_sviest", name:"Vilkyškių sviestas 82%",             category:"🇱🇹 Lietuviški produktai", kcal:738, protein:0.6,  fat:82,   carbs:0.7, units:[{label:"1 šaukštelis (5g)",grams:5},{label:"1 šaukštas (15g)",grams:15}] },
  { id:"vilk_sur",    name:"Vilkyškių sūris Džiugelis",          category:"🇱🇹 Lietuviški produktai", kcal:370, protein:25,   fat:29.5, carbs:0,   units:[{label:"1 riekelė (30g)",grams:30}] },

  // Kiti pieno produktai
  { id:"lindahls",    name:"Lindahls kvarg 0.2%",                category:"🇱🇹 Lietuviški produktai", kcal:63,  protein:11.3, fat:0.2,  carbs:4,   units:[{label:"1 indelis (150g)",grams:150}] },
  { id:"arla_skyr",   name:"Arla Skyr natūralus",                category:"🇱🇹 Lietuviški produktai", kcal:65,  protein:11,   fat:0.2,  carbs:4.5, units:[{label:"1 indelis (150g)",grams:150}] },
  { id:"arla_gr_jog", name:"Arla graikiškas jogurtas 2%",        category:"🇱🇹 Lietuviški produktai", kcal:73,  protein:9.5,  fat:2,    carbs:3.8, units:[{label:"1 indelis (150g)",grams:150}] },
  { id:"danone_activ",name:"Danone Activia natūralus",           category:"🇱🇹 Lietuviški produktai", kcal:62,  protein:4.3,  fat:2.8,  carbs:5.3, units:[{label:"1 indelis (125g)",grams:125}] },
  { id:"danone_jog",  name:"Danone Activia vaisinis jogurtas",   category:"🇱🇹 Lietuviški produktai", kcal:90,  protein:3.8,  fat:2.5,  carbs:13,  units:[{label:"1 indelis (125g)",grams:125}] },
  { id:"ehrmann_gr",  name:"Ehrmann Grand Dessert šokolado",     category:"🇱🇹 Lietuviški produktai", kcal:148, protein:4.8,  fat:7.5,  carbs:16,  units:[{label:"1 indelis (200g)",grams:200}] },

  // ═══ DUONA IR KEPYKLA ═══

  // Mantinga
  { id:"mant_juoda",  name:"Mantinga juoda ruginė duona",        category:"🇱🇹 Lietuviški produktai", kcal:215, protein:6.5,  fat:1.2,  carbs:44,  units:[{label:"1 riekelė (35g)",grams:35},{label:"2 riekelės",grams:70}] },
  { id:"mant_rugin",  name:"Mantinga ruginė duona",              category:"🇱🇹 Lietuviški produktai", kcal:229, protein:7.2,  fat:1.3,  carbs:46,  units:[{label:"1 riekelė (35g)",grams:35}] },
  { id:"mant_kviet",  name:"Mantinga kvietinė duona",            category:"🇱🇹 Lietuviški produktai", kcal:258, protein:8.5,  fat:2.8,  carbs:50,  units:[{label:"1 riekelė (35g)",grams:35}] },
  { id:"mant_sek",    name:"Mantinga duona su sėklomis",         category:"🇱🇹 Lietuviški produktai", kcal:248, protein:9.5,  fat:5.2,  carbs:40,  units:[{label:"1 riekelė (35g)",grams:35}] },
  { id:"fazer_rugin", name:"Fazer ruginė duona",                 category:"🇱🇹 Lietuviški produktai", kcal:200, protein:6,    fat:1,    carbs:41,  units:[{label:"1 riekelė (35g)",grams:35}] },
  { id:"wasa_rye",    name:"Wasa Crisp'n Light ruginiai skrebučiai", category:"🇱🇹 Lietuviški produktai", kcal:317, protein:10, fat:2.1, carbs:63, units:[{label:"1 vnt (8g)",grams:8},{label:"3 vnt",grams:24}] },

  // ═══ MESA GAMINIAI ═══
  { id:"mt_skiland",  name:"Mešų taurai skilandis",              category:"🇱🇹 Lietuviški produktai", kcal:335, protein:19.5, fat:28,   carbs:0,   units:[{label:"3 riekelės (30g)",grams:30},{label:"100g",grams:100}] },
  { id:"mt_kumpis",   name:"Mešų taurai virtas kumpis",          category:"🇱🇹 Lietuviški produktai", kcal:112, protein:18.5, fat:3.5,  carbs:2.5, units:[{label:"2 riekelės (50g)",grams:50},{label:"100g",grams:100}] },
  { id:"mt_desrele",  name:"Mešų taurai vištienos dešrelės",     category:"🇱🇹 Lietuviški produktai", kcal:155, protein:13,   fat:10.5, carbs:2.2, units:[{label:"1 vnt (60g)",grams:60}] },
  { id:"sams_krump",  name:"Samsonas rūkytas kumpis",            category:"🇱🇹 Lietuviški produktai", kcal:185, protein:20,   fat:11,   carbs:0,   units:[{label:"2 riekelės (50g)",grams:50}] },
  { id:"chorizo_lt",  name:"Chorizo tipo dešra",                 category:"🇱🇹 Lietuviški produktai", kcal:455, protein:24,   fat:38.3, carbs:2.5, units:[{label:"3 riekelės (30g)",grams:30}] },

  // ═══ ŽUVIS – VICI ir kiti ═══
  { id:"vici_pirsti", name:"VICI žuvų pirštai (kepti)",          category:"🇱🇹 Lietuviški produktai", kcal:220, protein:12,   fat:10,   carbs:21,  units:[{label:"4 vnt (100g)",grams:100},{label:"1 vnt (25g)",grams:25}] },
  { id:"vici_surimi", name:"VICI surimi lazdelės",               category:"🇱🇹 Lietuviški produktai", kcal:95,  protein:9.5,  fat:0.9,  carbs:12,  units:[{label:"1 lazdelė (15g)",grams:15},{label:"4 lazdelės",grams:60}] },
  { id:"vici_lasis",  name:"VICI lašiša rūkyta šaltai",         category:"🇱🇹 Lietuviški produktai", kcal:142, protein:22.5, fat:5.8,  carbs:0,   units:[{label:"3 riekelės (60g)",grams:60},{label:"100g",grams:100}] },
  { id:"vici_silke",  name:"VICI silkė aliejuje su svogūnais",   category:"🇱🇹 Lietuviški produktai", kcal:175, protein:14,   fat:12,   carbs:3,   units:[{label:"1 porcija (100g)",grams:100}] },
  { id:"vici_krevs",  name:"VICI krevetės virtos šaldytos",      category:"🇱🇹 Lietuviški produktai", kcal:82,  protein:18,   fat:0.8,  carbs:0.5, units:[{label:"1 porcija (100g)",grams:100}] },
  { id:"klk_silke",   name:"Klaipėdos konservai silkė marinuota", category:"🇱🇹 Lietuviški produktai", kcal:162, protein:16.5, fat:9.5, carbs:3.5, units:[{label:"1 filė (80g)",grams:80}] },
  { id:"klk_sprot",   name:"Klaipėdos konservai šprotai aliejuje", category:"🇱🇹 Lietuviški produktai", kcal:313, protein:18.5, fat:26, carbs:0, units:[{label:"½ skardinė (60g)",grams:60}] },

  // ═══ GRŪDAI IR PUSRYČIAI ═══
  { id:"herc_aviz",   name:"Hercules avižiniai dribsniai",       category:"🇱🇹 Lietuviški produktai", kcal:352, protein:13,   fat:6.2,  carbs:62,  units:[{label:"½ puodelio (40g)",grams:40},{label:"1 puodelis (80g)",grams:80}] },
  { id:"herc_inst",   name:"Hercules momentinės avižos",         category:"🇱🇹 Lietuviški produktai", kcal:360, protein:12,   fat:6,    carbs:64,  units:[{label:"1 paketėlis (35g)",grams:35}] },
  { id:"kell_cornfl", name:"Kellogg's Corn Flakes",              category:"🇱🇹 Lietuviški produktai", kcal:378, protein:7.5,  fat:0.9,  carbs:84,  units:[{label:"1 porcija (30g)",grams:30}] },
  { id:"kell_specK",  name:"Kellogg's Special K",                category:"🇱🇹 Lietuviški produktai", kcal:378, protein:14,   fat:1.5,  carbs:74,  units:[{label:"1 porcija (30g)",grams:30}] },
  { id:"kell_chocp",  name:"Kellogg's Choco Pops",               category:"🇱🇹 Lietuviški produktai", kcal:385, protein:5,    fat:3.5,  carbs:84,  units:[{label:"1 porcija (30g)",grams:30}] },
  { id:"quaker_aviz", name:"Quaker avižiniai dribsniai",         category:"🇱🇹 Lietuviški produktai", kcal:362, protein:12.5, fat:7.2,  carbs:60,  units:[{label:"½ puodelio (40g)",grams:40}] },
  { id:"fitness_drib",name:"Nestle Fitness dribsniai",           category:"🇱🇹 Lietuviški produktai", kcal:375, protein:9,    fat:2.5,  carbs:77,  units:[{label:"1 porcija (30g)",grams:30}] },

  // ═══ SALDUMYNAI ═══
  { id:"perg_pienis",  name:"Pergalė pieninis šokoladas",        category:"🇱🇹 Lietuviški produktai", kcal:536, protein:7.8,  fat:29.5, carbs:60,  units:[{label:"2 plytelės (20g)",grams:20},{label:"4 plytelės",grams:40}] },
  { id:"perg_juodas",  name:"Pergalė juodasis šokoladas 70%",    category:"🇱🇹 Lietuviški produktai", kcal:537, protein:7,    fat:37,   carbs:46,  units:[{label:"2 plytelės (20g)",grams:20}] },
  { id:"perg_migdol",  name:"Pergalė šokoladas su migdolais",    category:"🇱🇹 Lietuviški produktai", kcal:548, protein:8.5,  fat:33,   carbs:55,  units:[{label:"2 plytelės (20g)",grams:20}] },
  { id:"ruta_pienis",  name:"Rūta pieninis šokoladas",           category:"🇱🇹 Lietuviški produktai", kcal:530, protein:7.5,  fat:29,   carbs:61,  units:[{label:"2 plytelės (20g)",grams:20}] },
  { id:"ruta_karamel", name:"Rūta karamelių saldainiai",         category:"🇱🇹 Lietuviški produktai", kcal:397, protein:2.8,  fat:10,   carbs:73,  units:[{label:"3 vnt (20g)",grams:20}] },
  { id:"laima_pienis", name:"Laima pieninis šokoladas",          category:"🇱🇹 Lietuviški produktai", kcal:534, protein:8,    fat:30,   carbs:59,  units:[{label:"2 plytelės (20g)",grams:20}] },

  // ═══ UZKANDZIAI ═══
  { id:"chazz_solt",   name:"Chazz traškučiai sūdyti",           category:"🇱🇹 Lietuviški produktai", kcal:528, protein:6.5,  fat:33,   carbs:52,  units:[{label:"sauja (30g)",grams:30},{label:"mažas pakelis (50g)",grams:50}] },
  { id:"chazz_grot",   name:"Chazz traškučiai su grietinėle",    category:"🇱🇹 Lietuviški produktai", kcal:530, protein:6.2,  fat:33.5, carbs:52,  units:[{label:"sauja (30g)",grams:30}] },
  { id:"chazz_paprik", name:"Chazz traškučiai paprika",          category:"🇱🇹 Lietuviški produktai", kcal:527, protein:6.3,  fat:33,   carbs:52,  units:[{label:"sauja (30g)",grams:30}] },
  { id:"lays_solt",    name:"Lay's traškučiai sūdyti",           category:"🇱🇹 Lietuviški produktai", kcal:536, protein:7,    fat:34,   carbs:53,  units:[{label:"sauja (30g)",grams:30}] },
  { id:"lays_paprik",  name:"Lay's traškučiai paprika",          category:"🇱🇹 Lietuviški produktai", kcal:533, protein:6.5,  fat:33.5, carbs:53,  units:[{label:"sauja (30g)",grams:30}] },
  { id:"pring_orig",   name:"Pringles Original",                 category:"🇱🇹 Lietuviški produktai", kcal:524, protein:5.4,  fat:33.7, carbs:52,  units:[{label:"~10 vnt (30g)",grams:30}] },
  { id:"leibniz_but",  name:"Leibniz sviestiniai sausainiai",    category:"🇱🇹 Lietuviški produktai", kcal:487, protein:6.8,  fat:20,   carbs:69,  units:[{label:"3 sausainiai (30g)",grams:30}] },
  { id:"oreo",         name:"Oreo sausainiai",                   category:"🇱🇹 Lietuviški produktai", kcal:480, protein:5.5,  fat:21,   carbs:69,  units:[{label:"3 sausainiai (34g)",grams:34}] },
  { id:"digestive",    name:"McVitie Digestive sausainiai",      category:"🇱🇹 Lietuviški produktai", kcal:463, protein:7.2,  fat:20.3, carbs:63,  units:[{label:"2 sausainiai (29g)",grams:29}] },
  { id:"rivona_aviz",  name:"Rivona avižiniai sausainiai",       category:"🇱🇹 Lietuviški produktai", kcal:448, protein:7.5,  fat:18,   carbs:65,  units:[{label:"3 sausainiai (30g)",grams:30}] },

  // Baltymų batonėliai
  { id:"barebells_ch", name:"Barebells Protein Bar šokolado",    category:"🇱🇹 Lietuviški produktai", kcal:373, protein:20,   fat:15,   carbs:38,  units:[{label:"1 batonėlis (55g)",grams:55}] },
  { id:"quest_bar",    name:"Quest Protein Bar",                 category:"🇱🇹 Lietuviški produktai", kcal:376, protein:21,   fat:9,    carbs:44,  units:[{label:"1 batonėlis (60g)",grams:60}] },
  { id:"myp_prot_bar", name:"MyProtein Impact Protein Bar",      category:"🇱🇹 Lietuviški produktai", kcal:356, protein:22,   fat:10,   carbs:40,  units:[{label:"1 batonėlis (65g)",grams:65}] },

  // ═══ GERIMAI ═══
  { id:"cido_apel",    name:"Cido apelsinų sultys",              category:"🇱🇹 Lietuviški produktai", kcal:46,  protein:0.7,  fat:0.1,  carbs:10.6, units:[{label:"1 stiklinė (200ml)",grams:200}] },
  { id:"cido_obul",    name:"Cido obuolių sultys",               category:"🇱🇹 Lietuviški produktai", kcal:47,  protein:0.3,  fat:0.1,  carbs:11.2, units:[{label:"1 stiklinė (200ml)",grams:200}] },
  { id:"gira_birzai",  name:"Biržų gira",                        category:"🇱🇹 Lietuviški produktai", kcal:28,  protein:0.2,  fat:0,    carbs:7,   units:[{label:"1 stiklinė (200ml)",grams:200}] },
  { id:"redbull",      name:"Red Bull",                          category:"🇱🇹 Lietuviški produktai", kcal:45,  protein:0,    fat:0,    carbs:11,  units:[{label:"1 skardinė (250ml)",grams:250}] },
  { id:"monster_orig", name:"Monster Energy Original",           category:"🇱🇹 Lietuviški produktai", kcal:46,  protein:0,    fat:0,    carbs:11.3, units:[{label:"1 skardinė (500ml)",grams:500}] },
  { id:"jacobs_3in1",  name:"Jacobs Latte 3in1",                 category:"🇱🇹 Lietuviški produktai", kcal:387, protein:5,    fat:11.5, carbs:67,  units:[{label:"1 maišelis (12g)",grams:12}] },

  // ═══ PADAZAI IR KONSERVAI ═══
  { id:"babic_majones",name:"Babičiaus majonezas 67%",           category:"🇱🇹 Lietuviški produktai", kcal:620, protein:1.2,  fat:67,   carbs:5,   units:[{label:"1 šaukštas (15g)",grams:15}] },
  { id:"hortex_zirn",  name:"Hortex žirneliai šaldyti",          category:"🇱🇹 Lietuviški produktai", kcal:69,  protein:5,    fat:0.4,  carbs:12,  units:[{label:"½ puodelis (80g)",grams:80}] },
  { id:"hortex_brok",  name:"Hortex brokoliai šaldyti",          category:"🇱🇹 Lietuviški produktai", kcal:28,  protein:2.8,  fat:0.3,  carbs:4.5, units:[{label:"1 porcija (150g)",grams:150}] },
  { id:"bond_kukur",   name:"Bonduelle kukurūzai konservuoti",    category:"🇱🇹 Lietuviški produktai", kcal:86,  protein:3.2,  fat:1.2,  carbs:19,  units:[{label:"½ skardinė (100g)",grams:100}] },
  { id:"bond_zirnmor", name:"Bonduelle žirneliai ir morkos",     category:"🇱🇹 Lietuviški produktai", kcal:55,  protein:3.4,  fat:0.5,  carbs:10,  units:[{label:"½ skardinė (100g)",grams:100}] },

  // ═══ BALTYMU MILTELIAI ═══
  { id:"opt_whey",     name:"Optimum Nutrition Gold Standard Whey", category:"🇱🇹 Lietuviški produktai", kcal:402, protein:79, fat:5,    carbs:6,   units:[{label:"1 porcija (30g)",grams:30}] },
  { id:"myp_whey",     name:"MyProtein Impact Whey Protein",     category:"🇱🇹 Lietuviški produktai", kcal:392, protein:80,   fat:4.5,  carbs:5.5, units:[{label:"1 porcija (25g)",grams:25}] },

  // ═══ SALDYTI PATIEKALAI ═══
  { id:"nomad_cepel",  name:"Nomad šaldyti cepelinai su mėsa",   category:"🇱🇹 Lietuviški produktai", kcal:127, protein:6,    fat:4,    carbs:18,  units:[{label:"1 vnt (300g)",grams:300}] },
  { id:"vici_lazanija",name:"VICI lasagna su vištiena šaldyta",   category:"🇱🇹 Lietuviški produktai", kcal:132, protein:7.5,  fat:5.5,  carbs:14,  units:[{label:"1 porcija (300g)",grams:300}] },
];

// Sujungiame viška
export const ALL_FOODS = [...LOCAL_FOODS, ...EXTRA_FOODS, ...LT_BRANDED];

export function searchLocalFoods(query) {
  const q = query.toLowerCase().trim();
  if (!q) return ALL_FOODS.slice(0, 15);
  return ALL_FOODS.filter(f =>
    f.name.toLowerCase().includes(q) ||
    f.category.toLowerCase().includes(q)
  ).slice(0, 15);
}

export const CATEGORIES = [...new Set(ALL_FOODS.map(f => f.category))];
